### ISSUE TITLE
puzzles about densepose coco annotations

### ISSUE THREAD

**Issue by penincillin** [facebookresearch/DensePose#107]
Hi,
I am trying to use the  dense annotations you provide for coco dataset. But I have some puzzles about it.
When I try to draw point on the original images with coords come from 'dp_x' and 'dp_y', the points couldn't align with the people.  I guess during annotating,  the original images are first cropped into several patches according to the bbox and then those patches are cropped into the same size, I guess it is 256*256.
I have verified my guess and the resulting points could be roughly aligned with the person. But there are still some misalignment. Could please tell me the detailed process of cropping and rescaling?
For cropping. You just crop according to the bbox and thus get a rectangle (which couldn't be guaranteed to be a square) or you add some padding on the shorter side so that the resulting patches are guaranteed to be squared?
For scaling, the rescaled patches are guaranteed to be 256x256 (or other pre-defined size) or just the longer side is 256 and the aspect ratio of the original bbox is kept?
Thanks!

**Comment by penincillin** [comment]
Sorry, I misunderstand the form of bbox. It shall be bbox = [x1,y1, bbox_width, bbox_height]

**Comment by penincillin** [comment]
But I still not very clear about how to map the coords coming from 'dp_x' and 'dp_y' to the original images.
I have verified that through rescaling and translating the points could be roughly aligned with the person. But there are still some misalignment.  Could please tell me the detailed process of cropping and rescaling?
1. For cropping. You just crop out the person according to the bbox and get a rectangle or you add some padding on the shorted side so that the resulting images are guaranteed to be squared?
2. For scaling, the rescaled image is guaranteed to be 255x255 or just the longer side is 255 and the aspect ratio of the original bbox is kept?
Thanks!

**Comment by vkhalidov** [comment]
Please have a look at [this notebook](https://github.com/facebookresearch/DensePose/blob/master/notebooks/DensePose-COCO-Visualize.ipynb). It shows how to plot annotations on images.

**Comment by penincillin** [comment]
Thanks !
