### ISSUE TITLE
DensePose Bounding Boxes 

### ISSUE THREAD

**Issue by unfig** [facebookresearch/DensePose#108]
How can I extract the head, upper body and lower body using bounding boxes?

**Comment by ingramator** [comment]
As far as I'm aware the model only produces bounding box coordinates for the person as a whole not individual parts, however you could get a bounding box by finding the minimum bounding box for the segmented mask that is produced for each section. The entire body is segmented into multiple parts.

See [this page](https://github.com/facebookresearch/DensePose/blob/master/challenge/2018_COCO_DensePose/data_format.md) for specifications on how the data is labeled.
