### ISSUE TITLE
How to use this for real world dat sets?

### ISSUE THREAD

**Issue by jaggernaut07** [facebookresearch/DensePose#115]
I want to run this for my custom videos

**Comment by ingramator** [comment]
Please see issue #60 and use see this [repo](https://github.com/trrahul/densepose-video) for ease. Otherwise you will need to export all the frames in the video and run them as a batch through the inference.py script.

**Comment by jaggernaut07** [comment]
Yup figured out a way. Gonna run infer_simple on frames of the video and convert to smpl at the same time. Thanks for the reassured help! Always looking for alternate ways.

**Comment by jaggernaut07** [comment]
@ingramator smpl is the 3D model format. I am converting the video to have 3D models in it.

**Comment by ingramator** [comment]
@jaggernaut07 May I ask how you plan on doing that?

**Comment by jaggernaut07** [comment]
Gonna extract the key points from the posetrack . And put it on my smpl model. That's the plan. Do you have any better ways to implement this?

**Comment by ingramator** [comment]
@jaggernaut07 me and @ypflll have been discussing this problem at issue #55 ! Let me know how you go with your approach, ideally we want to actually fit the surface points that densepose generates for us since this will be far better accuracies

**Comment by jaggernaut07** [comment]
have you tried the approachused in PoseTrack/DensePose-PoseTrack-Visualize.ipynb? 
I was going about in using the same technique.
