### ISSUE TITLE
Test Accuracy Compared to Paper

### ISSUE THREAD

**Issue by landersson** [facebookresearch/DensePose#126]
Hi,

Running the following test_net.py commandline:
```
python2 tools/test_net.py --cfg configs/DensePose_ResNet50_FPN_s1x-e2e.yaml TEST.WEIGHTS https://s3.amazonaws.com/densepose/DensePose_ResNet50_FPN_s1x-e2e.pkl NUM_GPUS 1
```
I get the following body_uv accuracy:
```
INFO task_evaluation.py: 200: copypaste: 0.4892,0.8490,0.5078,0.4384,0.5059
```

The overall AP that I get, 0.4892, seems quite different from the one reported on the first row of Table 1 in the paper, i.e 51.0. 

Would you expect them to be more similar?

**Comment by WongKinYiu** [comment]
"Due to the new per-part normalization the AP numbers do not match those reported in the paper, which are obtained with global normalization factor K = 0.255."

**Comment by landersson** [comment]
Ok, thanks, that explains it. I'll close this issue.
