### ISSUE TITLE
Not able to install cocoAPI in python2 because of matplotlib error

### ISSUE THREAD

**Issue by Vuurtoren2000** [facebookresearch/DensePose#134]
Hello all,

I am trying to get Densepose running on my server with the following configuration also see my other issue #133:

    Operating system: Ubuntu 16.04
    Compiler version: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
    CUDA version: 9.0
    cuDNN version: 7.3.0
    NVIDIA driver version:
    GPU models (for all devices if they are not all the same): 2x Tesla V100
    python --version output: 2.7.12

I followed the installation in this link https://github.com/facebookresearch/DensePose/blob/master/INSTALL.md after I received a "Success" message of this command:

```
# To check if Caffe2 build was successful
python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
```

and when i issue the following command, the result is 2, which is correct.
```
# To check if Caffe2 GPU build was successful
# This must print a number > 0 in order to use Detectron
python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
```

When I try to install the cocoAPI with either of the following commands:
```
# COCOAPI=/path/to/clone/cocoapi
git clone https://github.com/cocodataset/cocoapi.git $COCOAPI
cd $COCOAPI/PythonAPI
# Install into global site-packages
make install
```
or
```
# Alternatively, if you do not have permissions or prefer
# not to install the COCO API into global site-packages
python2 setup.py install --user
```
I get the error:
```
Searching for matplotlib>=2.1.0
Reading https://pypi.org/simple/matplotlib
Downloading ttps://files.pythonhosted.org/packages/ec/06/def4f...
Best match: matplotlib 3.0.0
Processing matplotlib-3.0.0.tar.gz
Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3 or 3.4.
Beginning with Matplotlib 3.0, Python 3.5 and above is required.

This may be due to an out of date pip.

make sure you have pip >9.0.1.

Makefile:7: recipe for target 'install'failed
make: *** [install] Error 1
```

I get the errormessage that matplotlib 3.0 is necessary to run the cocoAPI. However matplotlib3.0 is not compatible with python2. With pip I can only download matploblib 1.5. I have pip version 18.

With python 3.7 I succesfully installed cocoAPI. But I am not sure if it is necessary to install cocoAPI in python2 to get detectron and densepose running.

Hope you can help me!

**Comment by JustinhoCHN** [comment]
You should use ```pip install matplotlib==2.1.0```

**Comment by JustinhoCHN** [comment]
Or you can try ```conda install matplotlib``` first, and then ```pip install --upgrade matplotlib==2.1.0```. I got that error too, but solved by the above command, DensePose doesn't need matplotlib 3.0.

**Comment by Vuurtoren2000** [comment]
Thanks a lot of your help Justin, this worked! Closing this issue.

**Comment by Vuurtoren2000** [comment]
Thanks a lot for your help Justin, this worked! Closing this issue.

**Comment by Vuurtoren2000** [comment]
By getting cocoAPI to work, this seems to solve the issue! Closing thread

**Comment by Vuurtoren2000** [comment]
Ok thanks, that is what I needed! I will close this thread

**Comment by Vuurtoren2000** [comment]
Thanks a lot Justin
