### ISSUE TITLE
Where could I download PROPOSAL_FILES: ('dense_coco_2014_train.pkl','dense_coco_2014_valminusminival.pkl')

### ISSUE THREAD

**Issue by zhhezhhe** [facebookresearch/DensePose#159]

**Comment by zhhezhhe** [comment]
I want to use DensePose_ResNet50_FPN.yaml to train a model by using 2 Gpus.

**Comment by lucasbrynte** [comment]
I have them, but I have no clue how / from where I got them.
Also I'm not sure what their purpose is. Do they contain annotated bounding boxes, or are they results from some kind of pretraining of the 1st stage detector?

**Comment by zhhezhhe** [comment]
@lucasbrynte this may help: https://github.com/facebookresearch/DensePose/issues/45   Because this is not end2end, so need to generate region proposals. So if we train an end2end model, we do not need these pkls. Thanks!

**Comment by lucasbrynte** [comment]
@zhhezhhe Thanks for nudging me in the right direction! Did you find the .pkl files? Seems like I downloaded them from AWS.

Btw, any idea what s1x stands for for some of the yaml configurations?

**Comment by zhhezhhe** [comment]
@lucasbrynte I did not find the pkl files. I do not know what s1x stands for, but I will put it here when I find the meaning.

**Comment by lucasbrynte** [comment]
Okay, for whatever it's worth have a look on all configs/XXX.yaml files. Some of them defines a relative path to the PROPOSAL_FILES (what you are observed). But many of them define a URL pointing to Amazon AWS instead.

So you can simply try to copy the URLs into the other config files. Or alternatively, download the .pkl files from AWS, and store them locally.

**Comment by xujin1184104394** [comment]
How do I download the dense_coco_2014_train.pkl and put it there?
