### ISSUE TITLE
How to apply my custom dataset to densepose pipeline?What is the proposal files for?

### ISSUE THREAD

**Issue by liangwx** [facebookresearch/DensePose#164]
I first converted my dataset to coco format and densepose format .
Then I added my dataset path into dataset_catalog.py and created the correct link to images directory and annotations path.
But when I am to train a model with command as followed:
`python2 tools/train_net.py \
    --cfg configs/DensePose_ResNet50_FPN_single_GPU.yaml \
    OUTPUT_DIR /tmp/detectron-output`
I got a "AssertionError":

> WARNING model_helper.py: 447: You are creating an op that the ModelHelper does not recognize: PoolPointsInterp.
WARNING model_helper.py: 447: You are creating an op that the ModelHelper does not recognize: PoolPointsInterp.
WARNING memonger.py:  55: NOTE: Executing memonger to optimize gradient memory
[I memonger.cc:236] Remapping 98 using 20 shared blobs.
INFO memonger.py:  97: Memonger memory optimization took 0.0108840465546 secs
[I context_gpu.cu:317] GPU 0: 151 MB
[I context_gpu.cu:321] Total: 151 MB
[I context_gpu.cu:317] GPU 0: 280 MB
[I context_gpu.cu:321] Total: 280 MB
[I context_gpu.cu:317] GPU 0: 411 MB
[I context_gpu.cu:321] Total: 411 MB
INFO train.py: 171: Loading dataset: ('dense_coco_2014_train', 'dense_coco_2014_valminusminival')
loading annotations into memory...
Done (t=0.40s)
creating index...
index created!
INFO json_dataset.py: 299: Loading proposals from: /tmp/detectron-download-cache/DensePose-RPN-train_fpn_resnet50.pkl
INFO json_dataset.py: 307:  1/350
Traceback (most recent call last):
  File "tools/train_net.py", line 119, in <module>
    main()
  File "tools/train_net.py", line 101, in main
    checkpoints = detectron.utils.train.train_model()
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/utils/train.py", line 50, in train_model
    setup_model_for_training(model, weights_file, output_dir)
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/utils/train.py", line 149, in setup_model_for_training
    add_model_training_inputs(model)
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/utils/train.py", line 173, in add_model_training_inputs
    cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/datasets/roidb.py", line 53, in combined_roidb_for_training
    roidbs = [get_roidb(*args) for args in zip(dataset_names, proposal_files)]
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/datasets/roidb.py", line 38, in get_roidb
    crowd_filter_thresh=cfg.TRAIN.CROWD_FILTER_THRESH
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/datasets/json_dataset.py", line 110, in get_roidb
    crowd_filter_thresh
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/datasets/json_dataset.py", line 310, in _add_proposals_from_file
    assert entry['id'] == proposals[id_field][i]
AssertionError

Then I turned to "DensePose_ResNet50_FPN_single_GPU.yaml", just commented out the"PROPOSAL_FILES"， but stil failed to train a model with error as following:

> WARNING memonger.py:  55: NOTE: Executing memonger to optimize gradient memory
[I memonger.cc:236] Remapping 98 using 20 shared blobs.
INFO memonger.py:  97: Memonger memory optimization took 0.01034283638 secs
[I context_gpu.cu:317] GPU 0: 151 MB
[I context_gpu.cu:321] Total: 151 MB
[I context_gpu.cu:317] GPU 0: 280 MB
[I context_gpu.cu:321] Total: 280 MB
[I context_gpu.cu:317] GPU 0: 411 MB
[I context_gpu.cu:321] Total: 411 MB
INFO train.py: 171: Loading dataset: ('dense_coco_2014_train', 'dense_coco_2014_valminusminival')
loading annotations into memory...
Done (t=0.40s)
creating index...
index created!
INFO roidb.py:  41: Appending horizontally-flipped training examples...
INFO roidb.py:  43: Loaded dataset: dense_coco_2014_train
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
INFO roidb.py:  41: Appending horizontally-flipped training examples...
INFO roidb.py:  43: Loaded dataset: dense_coco_2014_valminusminival
INFO roidb.py: 130: Filtered 0 roidb entries: 900 -> 900
INFO roidb.py:  59: Computing bounding-box regression targets...
INFO roidb.py:  61: done
INFO train.py: 175: 900 roidb entries
INFO net.py:  51: Loading weights from: /tmp/detectron-download-cache/R-50.pkl
INFO net.py:  80: fpn_inner_res5_2_sum_w not found
INFO net.py:  80: fpn_inner_res5_2_sum_b not found
INFO net.py:  80: fpn_inner_res4_5_sum_lateral_w not found
INFO net.py:  80: fpn_inner_res4_5_sum_lateral_b not found
INFO net.py:  80: fpn_inner_res3_3_sum_lateral_w not found
INFO net.py:  80: fpn_inner_res3_3_sum_lateral_b not found
INFO net.py:  80: fpn_inner_res2_2_sum_lateral_w not found
INFO net.py:  80: fpn_inner_res2_2_sum_lateral_b not found
INFO net.py:  80: fpn_res5_2_sum_w not found
INFO net.py:  80: fpn_res5_2_sum_b not found
INFO net.py:  80: fpn_res4_5_sum_w not found
INFO net.py:  80: fpn_res4_5_sum_b not found
INFO net.py:  80: fpn_res3_3_sum_w not found
INFO net.py:  80: fpn_res3_3_sum_b not found
INFO net.py:  80: fpn_res2_2_sum_w not found
INFO net.py:  80: fpn_res2_2_sum_b not found
INFO net.py:  80: fc6_w not found
INFO net.py:  80: fc6_b not found
INFO net.py:  80: fc7_w not found
INFO net.py:  80: fc7_b not found
INFO net.py:  80: cls_score_w not found
INFO net.py:  80: cls_score_b not found
INFO net.py:  80: bbox_pred_w not found
INFO net.py:  80: bbox_pred_b not found
INFO net.py:  80: body_conv_fcn1_w not found
INFO net.py:  80: body_conv_fcn1_b not found
INFO net.py:  80: body_conv_fcn2_w not found
INFO net.py:  80: body_conv_fcn2_b not found
INFO net.py:  80: body_conv_fcn3_w not found
INFO net.py:  80: body_conv_fcn3_b not found
INFO net.py:  80: body_conv_fcn4_w not found
INFO net.py:  80: body_conv_fcn4_b not found
INFO net.py:  80: body_conv_fcn5_w not found
INFO net.py:  80: body_conv_fcn5_b not found
INFO net.py:  80: body_conv_fcn6_w not found
INFO net.py:  80: body_conv_fcn6_b not found
INFO net.py:  80: body_conv_fcn7_w not found
INFO net.py:  80: body_conv_fcn7_b not found
INFO net.py:  80: body_conv_fcn8_w not found
INFO net.py:  80: body_conv_fcn8_b not found
INFO net.py:  80: AnnIndex_lowres_w not found
INFO net.py:  80: AnnIndex_lowres_b not found
INFO net.py:  80: Index_UV_lowres_w not found
INFO net.py:  80: Index_UV_lowres_b not found
INFO net.py:  80: U_lowres_w not found
INFO net.py:  80: U_lowres_b not found
INFO net.py:  80: V_lowres_w not found
INFO net.py:  80: V_lowres_b not found
INFO net.py:  80: AnnIndex_w not found
INFO net.py:  80: AnnIndex_b not found
INFO net.py:  80: Index_UV_w not found
INFO net.py:  80: Index_UV_b not found
INFO net.py:  80: U_estimated_w not found
INFO net.py:  80: U_estimated_b not found
INFO net.py:  80: V_estimated_w not found
INFO net.py:  80: V_estimated_b not found
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.00040968 secs
INFO train.py: 159: Outputs saved to: /tmp/detectron-output/train/dense_coco_2014_train:dense_coco_2014_valminusminival/generalized_rcnn
INFO loader.py: 221: Pre-filling mini-batch queue...
INFO loader.py: 226:   [0/64]
INFO loader.py: 226:   [0/64]
Traceback (most recent call last):
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/utils/coordinator.py", line 42, in stop_on_exception
    yield
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/loader.py", line 93, in minibatch_loader_thread
Traceback (most recent call last):
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/utils/coordinator.py", line 42, in stop_on_exception
    yield
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/loader.py", line 93, in minibatch_loader_thread
    blobs = self.get_next_minibatch()
    blobs = self.get_next_minibatch()
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/loader.py", line 126, in get_next_minibatch
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/loader.py", line 126, in get_next_minibatch
    blobs, valid = get_minibatch(minibatch_db)
    blobs, valid = get_minibatch(minibatch_db)
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/minibatch.py", line 77, in get_minibatch
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/minibatch.py", line 77, in get_minibatch
    valid = fast_rcnn_roi_data.add_fast_rcnn_blobs(blobs, im_scales, roidb)
    valid = fast_rcnn_roi_data.add_fast_rcnn_blobs(blobs, im_scales, roidb)
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/fast_rcnn.py", line 128, in add_fast_rcnn_blobs
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/fast_rcnn.py", line 128, in add_fast_rcnn_blobs
    frcn_blobs = _sample_rois(entry, im_scales[im_i], im_i)
    frcn_blobs = _sample_rois(entry, im_scales[im_i], im_i)
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/fast_rcnn.py", line 225, in _sample_rois
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/fast_rcnn.py", line 225, in _sample_rois
    blob_dict, sampled_boxes, roidb, im_scale, batch_idx
    blob_dict, sampled_boxes, roidb, im_scale, batch_idx
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/body_uv_rcnn.py", line 145, in add_body_uv_rcnn_blobs
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/roi_data/body_uv_rcnn.py", line 145, in add_body_uv_rcnn_blobs
    X_points[i, 0:len(GT_x)] = GT_x
    X_points[i, 0:len(GT_x)] = GT_x
ValueError: could not broadcast input array from shape (2189) into shape (196)
ValueError: could not broadcast input array from shape (1776) into shape (196)
INFO loader.py: 105: Stopping mini-batch loading thread
INFO loader.py: 105: Stopping mini-batch loading thread
INFO loader.py: 105: Stopping mini-batch loading thread
INFO loader.py: 105: Stopping mini-batch loading thread
INFO detector.py: 471: Changing learning rate 0.000000 -> 0.000025 at iter 0
[I net_async_base.h:196] Using specified CPU pool size: 4; device id: -1
[I net_async_base.h:201] Created new CPU pool, size: 4; device id: -1
[E net_async_base.cc:372] Failed to execute an op,  op DequeueBlobs
WARNING workspace.py: 187: Original python traceback for operator `0` in network `generalized_rcnn` in exception above (most recent call last):
WARNING workspace.py: 192:   File "tools/train_net.py", line 119, in <module>
WARNING workspace.py: 192:   File "tools/train_net.py", line 101, in main
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/utils/train.py", line 45, in train_model
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/utils/train.py", line 124, in create_model
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/modeling/model_builder.py", line 119, in create
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/modeling/model_builder.py", line 84, in generalized_rcnn
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/modeling/model_builder.py", line 233, in build_generic_detection_model
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/modeling/optimizer.py", line 32, in build_data_parallel_model
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/modeling/optimizer.py", line 55, in _build_forward_graph
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/modeling/model_builder.py", line 165, in _single_gpu_build_func
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/modeling/FPN.py", line 40, in add_fpn_ResNet50_conv5_body
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/modeling/FPN.py", line 96, in add_fpn_onto_conv_body
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/modeling/ResNet.py", line 32, in add_ResNet50_conv5_body
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/modeling/ResNet.py", line 90, in add_ResNet_convX_body
WARNING workspace.py: 192:   File "/media/Data/wangxiaoliang/densepose/densepose/detectron/modeling/ResNet.py", line 243, in basic_bn_stem
WARNING workspace.py: 192:   File "/home/wangxiaoliang/miniconda2/lib/python2.7/site-packages/caffe2/python/cnn.py", line 97, in Conv
WARNING workspace.py: 192:   File "/home/wangxiaoliang/miniconda2/lib/python2.7/site-packages/caffe2/python/brew.py", line 107, in scope_wrapper
WARNING workspace.py: 192:   File "/home/wangxiaoliang/miniconda2/lib/python2.7/site-packages/caffe2/python/helpers/conv.py", line 186, in conv
WARNING workspace.py: 192:   File "/home/wangxiaoliang/miniconda2/lib/python2.7/site-packages/caffe2/python/helpers/conv.py", line 139, in _ConvBase
Traceback (most recent call last):
  File "tools/train_net.py", line 119, in <module>
    main()
  File "tools/train_net.py", line 101, in main
    checkpoints = detectron.utils.train.train_model()
  File "/media/Data/wangxiaoliang/densepose/densepose/detectron/utils/train.py", line 57, in train_model
    workspace.RunNet(model.net.Proto().name)
  File "/home/wangxiaoliang/miniconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 219, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/wangxiaoliang/miniconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:1141] success. Error running net generalized_rcnn
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x76 (0x7fe76e0b4006 in /home/wangxiaoliang/miniconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: <unknown function> + 0x49736 (0x7fe780684736 in /home/wangxiaoliang/miniconda2/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
frame #2: <unknown function> + 0x93ce0 (0x7fe7806cece0 in /home/wangxiaoliang/miniconda2/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)<omitting python frames>
frame #18: __libc_start_main + 0xf0 (0x7fe7b6feb830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #19: <unknown function> + 0x8bf (0x55ffd29ff8bf in python2)

I don't know if the proposal files is corresponding to densepose dataset. And I just wanna my own dataset to work in traing a densepose model. Any information would be helpful ,Thanks!!!

**Comment by tjzjp** [comment]
I met the same problem:
assert entry['id'] == proposals[id_field][i]
have you solved it?
