### ISSUE TITLE
Open source the annotation system

### ISSUE THREAD

**Issue by Alan-Paul** [facebookresearch/DensePose#174]
Hello there,thanks for the great work in advanced!
we want to apply the models to our own dataset only to find that performances not well. we want to train a model on our own dataset but do not have an appropriate annotation system.we will be grateful if you can open source your annotation system!
thank you again !

**Comment by zhangy76** [comment]
Hey,

Have you found any annotation system?

Best,
Yufei

**Comment by guangdongliang** [comment]
@Alan-Paul hello @zhangy76 
      have you got the annotation system, I think with the system, the densepose idea can make great contribution to computer vision !
 
looking forward to your replay .

**Comment by zhangy76** [comment]
Hi,

I did not get any annotation system and just annotate with image and 3D model.

**Comment by guangdongliang** [comment]
@zhangy76 
Thank you very much for your replay.  I will build my annotation system follow your advice .
