### ISSUE TITLE
Test with Movie

### ISSUE THREAD

**Issue by ogata2606** [facebookresearch/DensePose#18]
Thanks you to publish source code.
I could test demo image and own image.
But I cannot test with own movie.
So, are there any way to test with movie?

**Comment by joel-huang** [comment]
I tested the pre-trained model using frame-by-frame inference on webcam, works fine albeit at a paltry <10 FPS. Why can't you test with video?

**Comment by ogata2606** [comment]
Really?
I'd like to know how did you test with webcam.
Such as command, camera, etc...

**Comment by zengfanyi** [comment]
U are so cool.can i do this by pytroch?

**Comment by Tetsujinfr** [comment]
Hi Joel, can you share your inference results?
Thanks

**Comment by vkhalidov** [comment]
The code in [infer_simple.py](https://github.com/facebookresearch/DensePose/blob/master/tools/infer_simple.py) can process a sequence of images from a folder. You can modify the code to process images streamed from your webcam.

**Comment by MuhammadAsadJaved** [comment]
Hi , my code is working on singe image . Can anyone share code how to test DensePose on video file?
