### ISSUE TITLE
Bug report on densepose_cocoeval.py

### ISSUE THREAD

**Issue by penincillin** [facebookresearch/DensePose#182]
Hi, I am currently reading the source code of densepose, and I think there might be a bug in [detectron/datasets/densepose_cocoeval.py](https://github.com/facebookresearch/DensePose/blob/master/detectron/datasets/densepose_cocoeval.py). Don't be nervous, this bug won't affect the result of the code, it will just confuse people like me who try to read your code :)
From line 378 to line 397 I think some 'x' and 'y' are messed up and the code with correct use of 'x' and 'y' should be :
Line 378~379:
```python
dy = dt['bbox'][3] 
dx = dt['bbox'][2]
```
Line 382~383
```python
py = ( dp_y + g_[1] - dt['bbox'][1]).astype(np.int)
px = ( dp_x + g_[0] - dt['bbox'][0]).astype(np.int)
```
Line 395~397
```python
ipoints = dt['uv'][0, py, px]
upoints = dt['uv'][1, py, px]/255. # convert from uint8 by /255.
vpoints = dt['uv'][2, py, px]/255.
```

I would appreciate if you reply me. 
Thanks !

**Comment by vkhalidov** [comment]
@penincillin Indeed, the names `x` and `y` are partly interchanged here. Bounding box dimensions `dx` and `dy` computed [on lines 378-379](https://github.com/facebookresearch/DensePose/blob/master/detectron/datasets/densepose_cocoeval.py#L378) and point coordinates `px` and `py` computed [on lines 382-383](https://github.com/facebookresearch/DensePose/blob/master/detectron/datasets/densepose_cocoeval.py#L382) refer in fact to `y` and `x` coordinates respectively. At the same time, `dp_x` and `dp_y` variables refer to `x` and `y` respectively. This creates syntactic confusion, but the code is semantically correct.

**Comment by penincillin** [comment]
Thanks for your reply !
I got it.

**Comment by Johnqczhang** [comment]
@vkhalidov @penincillin I fixed this confusion and simplified the code in #203, which makes the code understood more easily and has no effect on the results.
