### ISSUE TITLE
Can't download the Pretrained model R-50.pkl : http error 404 not found

### ISSUE THREAD

**Issue by Alan-Paul** [facebookresearch/DensePose#186]
Thanks for the great work in advanced !
        I found that 404 error when i try to test/train a model following the [GETTING_STARTED.md](
        DensePose/GETTING_STARTED.md)
![image](https://user-images.githubusercontent.com/26460930/51254158-5d93a480-19db-11e9-917b-e9b10409727c.png)
        It seems that i can not download the /ImageNetPretrained/MSRA/R-50.pkl successfully ！
        Sorry to bother you ~
        Any advice will be appreciated !

**Comment by vkhalidov** [comment]
@Alan-Paul Please be sure to apply recent update #181 which defines new URLs for the pretrained models (check [DensePose_ResNet50_FPN.yaml](https://github.com/facebookresearch/DensePose/blob/master/configs/DensePose_ResNet50_FPN.yaml#L61) for instance)

**Comment by Alan-Paul** [comment]
done ! thank you
