### ISSUE TITLE
Error running DP.IUV2FBC/DP.IUV2FBC_fast

### ISSUE THREAD

**Issue by 09panesara** [facebookresearch/DensePose#187]
Hi,

I am getting the following error when running `FaceIndex,bc1,bc2,bc3 = DP.IUV2FBC_fast(IUV_pick[i, 0], IUV_pick[i, 1], IUV_pick[i, 2])` as per [this](https://github.com/davidleejy/DensePose/blob/speedup/notebooks/DensePose-Fast-IUV-2-XYZ.ipynb) notebook: 
ValueError: zero-size array to reduction operation minimum which has no identity.
I even get this error when running the original method DP.IUVFBC. 

Tested on both my own IUV and the example from the DensePose-Fast-IUV-2-XYZ demo referenced above. 

Any help would be much appreciated.

**Comment by vkhalidov** [comment]
@09panesara it's hard to tell without any stack trace. You need to check which array is empty and why.

**Comment by 09panesara** [comment]
@vkhalidov After a fresh installation, this was no longer an issue. I had mixed the installation from densepose and davidleejy's densepose which perhaps was causing issues somewhere along the line.

**Comment by wine3603** [comment]
I got the same error .....
