### ISSUE TITLE
Demo_dp_single_ann.pkl

### ISSUE THREAD

**Issue by murthy-dev** [facebookresearch/DensePose#19]
demo_dp_single_ann.pkl file is missing from the demo_data directory 
Could you guide how to generate this output pkl  file ?

**Comment by vkhalidov** [comment]
The file was added in [commit 672f3975aa8ef14702ded5af55291d0ac73d638a](https://github.com/facebookresearch/DensePose/commit/672f3975aa8ef14702ded5af55291d0ac73d638a)
