### ISSUE TITLE
Problem with running infer.py

### ISSUE THREAD

**Issue by Shoulder95** [facebookresearch/DensePose#196]
I have run infer_simple.py successfully but now  I want to run infer.py with the following command

python2 tools/infer.py \
--im /ImageSamples/12.jpg \
--rpn-pkl https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl \
--rpn-cfg configs/rpn_densepose_only_R-50-FPN_1x.yaml \
--output-dir DensePoseData/infer_out_demo/ \
/tmp/detectron-download-cache/R-50.pkl configs/DensePoseKeyPointsMask_ResNet50_FPN_s1x-e2e.yaml

doing this throws the following error

WARNING cnn.py:  40: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  51: Loading weights from: /tmp/detectron-download-cache/R-50.pkl
INFO net.py:  80: fpn_inner_res5_2_sum_w not found
INFO net.py:  80: fpn_inner_res5_2_sum_b not found
INFO net.py:  80: fpn_inner_res4_5_sum_lateral_w not found
INFO net.py:  80: fpn_inner_res4_5_sum_lateral_b not found
INFO net.py:  80: fpn_inner_res3_3_sum_lateral_w not found
INFO net.py:  80: fpn_inner_res3_3_sum_lateral_b not found
INFO net.py:  80: fpn_inner_res2_2_sum_lateral_w not found
INFO net.py:  80: fpn_inner_res2_2_sum_lateral_b not found
INFO net.py:  80: fpn_res5_2_sum_w not found
INFO net.py:  80: fpn_res5_2_sum_b not found
INFO net.py:  80: fpn_res4_5_sum_w not found
INFO net.py:  80: fpn_res4_5_sum_b not found
INFO net.py:  80: fpn_res3_3_sum_w not found
INFO net.py:  80: fpn_res3_3_sum_b not found
INFO net.py:  80: fpn_res2_2_sum_w not found
INFO net.py:  80: fpn_res2_2_sum_b not found
INFO net.py:  80: conv_rpn_fpn2_w not found
INFO net.py:  80: conv_rpn_fpn2_b not found
INFO net.py:  80: rpn_cls_logits_fpn2_w not found
INFO net.py:  80: rpn_cls_logits_fpn2_b not found
INFO net.py:  80: rpn_bbox_pred_fpn2_w not found
INFO net.py:  80: rpn_bbox_pred_fpn2_b not found
I0204 07:40:28.772910    44 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 0.000119152 secs
I0204 07:40:28.773098    44 net_dag.cc:61] Number of parallel execution chains 52 Number of operators = 218
I0204 07:40:28.788821    44 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 0.000100354 secs
I0204 07:40:28.788954    44 net_dag.cc:61] Number of parallel execution chains 30 Number of operators = 188
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at blob.h:94] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/fpn_inner_res2_2_sum_lateral_w.
Error from operator: 
input: "gpu_0/res2_2_sum" input: "gpu_0/fpn_inner_res2_2_sum_lateral_w" input: "gpu_0/fpn_inner_res2_2_sum_lateral_b" output: "gpu_0/fpn_inner_res2_2_sum_lateral" name: "" type: "Conv" arg { name: "kernel" i: 1 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 0 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
*** Aborted at 1549266030 (unix time) try "date -d @1549266030" if you are using GNU date ***
PC: @     0x7f1c3d5ed428 gsignal
*** SIGABRT (@0x2c) received by PID 44 (TID 0x7f1b53fff700) from PID 44; stack trace: ***
    @     0x7f1c3d993390 (unknown)
    @     0x7f1c3d5ed428 gsignal
    @     0x7f1c3d5ef02a abort
    @     0x7f1c3763284d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f1c376306b6 (unknown)
    @     0x7f1c37630701 std::terminate()
    @     0x7f1c3765bd38 (unknown)
    @     0x7f1c3d9896ba start_thread
    @     0x7f1c3d6bf41d clone
    @                0x0 (unknown)
Aborted (core dumped)

I am running it in the Docker with a GTX 1080 card

**Comment by vkhalidov** [comment]
@Shoulder95 you're using ResNet50 to inisitalize RPN, so the uninitialized blob error is expected. What are you trying to achieve?

**Comment by Shoulder95** [comment]
I am just trying to run the infer.py tool on a image with the DensePoseKeyPointsMask_ResNet50_FPN_s1x-e2e.yaml. What I am after is the .pkl file that the script returns. 

I have tried to follow this instruction found in the infer.py file.

# infer.py
#   --im [path/to/image.jpg]
#   --rpn-model [path/to/rpn/model.pkl]
#   --rpn-config [path/to/rpn/config.yaml]
#   [model1] [config1] [model2] [config2] ...

Should I have something else in these arguments?
