### ISSUE TITLE
cd $DensePose && make ops

### ISSUE THREAD

**Issue by Molength** [facebookresearch/DensePose#20]
cd $DensPose && make ops
when I perform this instruction , it will tell me that 
‘
mkdir -p build && cd build && cmake .. && make -j48
-- Caffe2: Cannot find gflags automatically. Using legacy find.
-- Caffe2: Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Caffe2: Found glog (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe2: Found protobuf with old-style protobuf targets.
-- Caffe2: Protobuf version
CMake Error at /data/xiaobing.wang/peixuan.liang/caffe2/build/Caffe2Config.cmake:55 (message):
  Your installed Caffe2 is built with protobuf , while your current cmake
  setting discovers protobuf version .  Please specify a protobuf version
  that is the same as the built version.
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)

-- Configuring incomplete, errors occurred!
See also "/data/xiaobing.wang/peixuan.liang/DensePose-master/build/CMakeFiles/CMakeOutput.log".
See also "/data/xiaobing.wang/peixuan.liang/DensePose-master/build/CMakeFiles/CMakeError.log".
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 1

’
and i could not solve this problem，what should i do?
thanks very much.

**Comment by vkhalidov** [comment]
Could you please provide more details on the failure, e.g. CMake logs?

**Comment by Molength** [comment]
mkdir -p build && cd build && cmake .. && make -j48
CMake Error at /data/xiaobing.wang/caffe2/build/Caffe2Config.cmake:14 (include):
  include could not find load file:

    /data/xiaobing.wang/caffe2/build/public/utils.cmake
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)


CMake Error at /data/xiaobing.wang/caffe2/build/Caffe2Config.cmake:19 (include):
  include could not find load file:

    /data/xiaobing.wang/caffe2/build/public/gflags.cmake
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)


CMake Error at /data/xiaobing.wang/caffe2/build/Caffe2Config.cmake:21 (message):
  Your installed Caffe2 version uses gflags but the gflags library cannot be
  found.  Did you accidentally remove it, or have you set the right
  CMAKE_PREFIX_PATH and/or GFLAGS_ROOT_DIR? If you do not have gflags, you
  will need to install gflags and set the library path accordingly.
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
See also "/data/xiaobing.wang/zhiang.hao/DensePose-master/build/CMakeFiles/CMakeOutput.log".
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 1

**Comment by Molength** [comment]
mkdir -p build && cd build && cmake .. && make -j48
CMake Error at /data/caffe2/build/Caffe2Config.cmake:14 (include):
  include could not find load file:

    /data/caffe2/build/public/utils.cmake
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)


CMake Error at /data/caffe2/build/Caffe2Config.cmake:19 (include):
  include could not find load file:

    /data/caffe2/build/public/gflags.cmake
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)


CMake Error at /data/caffe2/build/Caffe2Config.cmake:21 (message):
  Your installed Caffe2 version uses gflags but the gflags library cannot be
  found.  Did you accidentally remove it, or have you set the right
  CMAKE_PREFIX_PATH and/or GFLAGS_ROOT_DIR? If you do not have gflags, you
  will need to install gflags and set the library path accordingly.
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
See also "/data/zhiang.hao/DensePose-master/build/CMakeFiles/CMakeOutput.log".
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 1

**Comment by vkhalidov** [comment]
Now answering the edited question: you should check your Caffe2 installation, in particular where the *.cmake files are installed.

**Comment by djangogo** [comment]
Have you installed the caffe2 according to the installation guide in caffe2 website?
It seems that the cmake can not find the some cmake files from caffe2

**Comment by ofirnabati** [comment]
Hi, 

I also have a problem with this command. 
I got the next log:
mkdir -p build && cd build && cmake .. && make -j8
-- Caffe2: Cannot find gflags automatically. Using legacy find.
-- Caffe2: Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.5.0
-- Caffe2: CUDA detected: 8.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 8.0
-- Found cuDNN: v6.0.21  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s): 6.1 
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Summary:
--   CMake version        : 3.5.1
--   CMake command        : /usr/bin/cmake
--   System name          : Linux
--   C++ compiler         : /usr/bin/c++
--   C++ compiler version : 5.4.0
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 0.8.2
--   Caffe2 include path  : /usr/local/include
--   Caffe2 found CUDA    : 
CMake Error at CMakeLists.txt:41 (if):
  if given arguments:

    "ON" "OR"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/home/multiview/ofir/Denspose/densepose/build/CMakeFiles/CMakeOutput.log".
See also "/home/multiview/ofir/Denspose/densepose/build/CMakeFiles/CMakeError.log".
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 1

Thanks for the help

**Comment by vkhalidov** [comment]
Thanks for reporting this, #28 should fix the issue

**Comment by nbjunjie** [comment]
Hi,

when I  execute the command "make ops"
I also have a problem similiar.
I got the next log:
mkdir -p build && cd build && cmake .. && make -j16
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Caffe2: Found glog (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.5.0
CMake Warning at /usr/local/share/cmake-3.11/Modules/FindCUDA.cmake:887 (message):
  Expecting to find librt for libcudart_static, but didn't find it.
Call Stack (most recent call first):
  /home/m525/anaconda2/share/cmake/Caffe2/public/cuda.cmake:6 (find_package)
  /home/m525/anaconda2/share/cmake/Caffe2/Caffe2Config.cmake:74 (include)
  CMakeLists.txt:8 (find_package)


-- Caffe2: CUDA detected: 8.0
-- Found cuDNN: v7.0.5  (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
-- Automatic GPU detection returned 6.1.
-- Added CUDA NVCC flags for: sm_61
-- Summary:
--   CMake version        : 3.11.4
--   CMake command        : /usr/local/bin/cmake
--   System name          : Linux
--   C++ compiler         : /home/m525/anaconda2/bin/c++
--   C++ compiler version : 5.2.0
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 0.8.2
--   Caffe2 include path  : /home/m525/anaconda2/include
--   Caffe2 found CUDA    : TRUE
--     CUDA version       : 8.0
--     CuDNN version      : 7.0.5
CMake Error at CMakeLists.txt:41 (if):
  if given arguments:

    "OR" "TRUE"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/home/m525/densepose/build/CMakeFiles/CMakeOutput.log".
See also "/home/m525/densepose/build/CMakeFiles/CMakeError.log".
make: *** [ops] Error 1

**Comment by vkhalidov** [comment]
@nbjunjie could you please detail on what the error was when you tried #28 ? It cannot be the same, since the variables' contents is no longer substituted into the `if` operator arguments. Please also note that #28 is now merged into the master.

**Comment by nbjunjie** [comment]
@vkhalidov Yes,after I tried #28,error is not the same before. the exact error I haven‘t maintain，but it's similar bellow,I can only show the error After I degrade my CMake version now.
For the CMake Error at CMakeLists.txt:41 :
I wonder if my Cmake version(3.11.4) is to high to built this program，
so I degrade my CMake version from 3.11.4 to (< 3.7)3.6.3,
and  execute "make clean" --> "make" -->"make ops"
when I execute the command "make ops",
I got the next log:
mkdir -p build && cd build && cmake .. && make -j16
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Found glog: /usr/local/include  
-- Caffe2: Found glog (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.5.0
-- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "7.0") 
-- Found CUDNN: /usr/local/cuda-8.0/include  
-- Caffe2: CUDA detected: 8.0
-- Found cuDNN: v7.0.5  (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
-- Automatic GPU detection returned 6.1.
-- Added CUDA NVCC flags for: sm_61
-- Summary:
--   CMake version        : 3.6.3
--   CMake command        : /usr/local/bin/cmake
--   System name          : Linux
--   C++ compiler         : /usr/bin/c++
--   C++ compiler version : 4.8.4
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 0.8.2
--   Caffe2 include path  : /home/m525/anaconda2/include
--   Caffe2 found CUDA    : True
--     CUDA version       : 8.0
--     CuDNN version      : 7.0.5
-- Configuring done
-- Generating done
-- Build files have been written to: /home/m525/densepose/build
make[1]: Entering directory `/home/m525/densepose/build'
make[2]: Entering directory `/home/m525/densepose/build'
make[3]: Entering directory `/home/m525/densepose/build'
make[3]: Entering directory `/home/m525/densepose/build'
[ 25%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o
[ 25%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o
Scanning dependencies of target caffe2_detectron_custom_ops
make[3]: Leaving directory `/home/m525/densepose/build'
make[3]: Entering directory `/home/m525/densepose/build'
[ 50%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
[ 50%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
[ 62%] Linking CXX shared library libcaffe2_detectron_custom_ops.so
/usr/bin/ld: /home/m525/anaconda2/lib/libprotobuf.a(descriptor.o): unrecognized relocation (0x29) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[3]: *** [libcaffe2_detectron_custom_ops.so] Error 1
make[3]: Leaving directory `/home/m525/densepose/build'
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target caffe2_detectron_custom_ops_gpu
make[3]: Leaving directory `/home/m525/densepose/build'
make[3]: Entering directory `/home/m525/densepose/build'
[ 75%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/pool_points_interp.cc.o
[ 87%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/zero_even_op.cc.o
[100%] Linking CXX shared library libcaffe2_detectron_custom_ops_gpu.so
/usr/bin/ld: /home/m525/anaconda2/lib/libprotobuf.a(descriptor.o): unrecognized relocation (0x29) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[3]: *** [libcaffe2_detectron_custom_ops_gpu.so] Error 1
make[3]: Leaving directory `/home/m525/densepose/build'
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all] Error 2
make[2]: Leaving directory `/home/m525/densepose/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/m525/densepose/build'
make: *** [ops] Error 2 


I still haven't made it clear whether the error‘s occur is related to Cmake version？

**Comment by vkhalidov** [comment]
please use the same build tools for DensePose as you used for detectron or Caffe2

**Comment by djangogo** [comment]
Hi @nbjunjie 
# Problem:
if given arguments:

"OR" "TRUE"
Unknown arguments specified


# Solution
Assume you have already installed caffe2 successfully.
My solution is to add SET(CAFFE2_FOUND_CUDA ON) to CMakeLists.txt

```
# Install custom GPU ops lib, if gpu is present.
SET(CAFFE2_FOUND_CUDA ON) # I add this here

if (${CAFFE2_USE_CUDA} OR ${CAFFE2_FOUND_CUDA})
  # Additional -I prefix is required for CMake versions before commit (< 3.7):
  # https://github.com/Kitware/CMake/commit/7ded655f7ba82ea72a82d0555449f2df5ef38594
  list(APPEND CUDA_INCLUDE_DIRS -I${CAFFE2_INCLUDE_DIRS})
  CUDA_ADD_LIBRARY(
      caffe2_detectron_custom_ops_gpu SHARED
      ${CUSTOM_OPS_CPU_SRCS}
      ${CUSTOM_OPS_GPU_SRCS})

  target_link_libraries(caffe2_detectron_custom_ops_gpu caffe2_gpu_library)
  install(TARGETS caffe2_detectron_custom_ops_gpu DESTINATION lib)
endif()
```

**Comment by vkhalidov** [comment]
@djangogo you should not modify the original `CMakeLists.txt` file. The current master branch does not have the mentioned issue since #28 has been merged.

**Comment by nbjunjie** [comment]
@vkhalidov It may relate  to build tool version,I install Caffe2 by conda install method,which contianed libProtobuf install already.
I solved this link error when I build the Protobuf from source code of Caffe2,and replace the libprotobuf.a.

**Comment by nbjunjie** [comment]
@vkhalidov @djangogo Thanks!
It may relate  to build tool version,I install Caffe2 by conda install method,which contianed libProtobuf already.
According to[Protobuf Errors](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md#protobuf-errors)
I solved this link error when I build the Protobuf from source code of Caffe2,and replace the libprotobuf.a.

**Comment by vkhalidov** [comment]
@nbjunjie right, there might be a conflict with the system libprotobuf if you use a new PyTorch installation of Caffe2, which by default embeds its own version of protocol buffers into Caffe2. There are 2 solutions: 1) either use PyTorch / Caffe2 protocol buffers everywhere, or 2) configure PyTorch / Caffe2 to use external protocol buffers through CMake options
