### ISSUE TITLE
Puzzles about code

### ISSUE THREAD

**Issue by penincillin** [facebookresearch/DensePose#200]
Hi, I am reading the code  [body_uv_rcnn_head.py](https://github.com/facebookresearch/DensePose/blob/master/detectron/modeling/body_uv_rcnn_heads.py#L46). Code in  [line 46](https://github.com/facebookresearch/DensePose/blob/35e69d110b432704c2183cd6aea531f4f695edbe/detectron/modeling/body_uv_rcnn_heads.py#L46) sets both the input and output dim to be 25, but the [line 26](https://github.com/facebookresearch/DensePose/blob/35e69d110b432704c2183cd6aea531f4f695edbe/detectron/modeling/body_uv_rcnn_heads.py#L26) specifices the output dim of AnnIndex_lowres to be 15 instead of 25.  So I am puzzled about it.
Hope you could reply me, thanks !

**Comment by Johnqczhang** [comment]
`AnnIndex_lowres` and `AnnIndex` are two different `ConvTranspose` layers, the latter takes input as the former.

**Comment by penincillin** [comment]
Thanks for your reply !
But I am still puzzled. What do you mean by " the latter takes input as the former ". 
My understanding is that AnnIndex takes AnnIndex_lowres as input. But the output dim of AnnIndex_loweres is 15 but the input dim of AnnIndex is 25. That is what I confused about .

**Comment by Johnqczhang** [comment]
@penincillin What I mean is exactly the same as what you said.

The output dim of `AnnIndex` is 25, which represents 24 defined body parts and 1 background. As for the output dim of `AnnIndex_lowres` which is 15, I don't think it represents any physical meaning, since `AnnIndex_lowres` just output feature maps with lower resolution than the output of `AnnIndex`. Maybe it's just a consideration of controlling the number of learnable parameters.

**Comment by penincillin** [comment]
@Johnqczhang thanks for you reply. However, `AnnIndex` refers to body part segmentation whose output dim should be 15. If you have check the value of `AnnIndex`, you will find that only the first 15 channels have response.

**Comment by Johnqczhang** [comment]
@penincillin I haven't checked the value of `AnnIndex` yet. I agree with you that `AnnIndex` refers to body part segmentation as the first stage of DensePose annotation pipeline given in the second paragraph of section 2.1 of the paper, in which you can see there are 24 parts (plus background) resulting from the part segmentation. So, I'm not sure why the output dim of `AnnIndex` should be 15 by what you said. As for "only the first 15 channels have response", one possible reason for this is that some body parts are invisible (e.g., the backside of torso when a person faces to the camera). Besides, generally the first channel of the output corresponds to the "background" class, which should have no response.

If you check the code of inference (https://github.com/facebookresearch/DensePose/blob/master/detectron/core/test.py#L951), you can see that `AnnIndex` has the same dimension of output with the estimated body_I/U/V. One thing puzzles me is that I wonder why the author named this variable as `AnnIndex` for part segmentation. At first, com.eusoft.eudic.plist

**Comment by Johnqczhang** [comment]
@penincillin I haven't checked the value of `AnnIndex` yet. I agree with you that `AnnIndex` refers to body part segmentation as the first stage of DensePose annotation pipeline given in the second paragraph of section 2.1 of the paper, in which you can see there are 24 parts (plus background) resulting from the part segmentation. So, I'm not sure why the output dim of `AnnIndex` should be 15 by what you said. As for "only the first 15 channels have response", one possible reason for this is that some body parts are invisible (e.g., the backside of torso when a person faces to the camera). Besides, generally the first channel of the output corresponds to the "background" class, which should have no response.

If you check the code of inference (https://github.com/facebookresearch/DensePose/blob/master/detectron/core/test.py#L951), you can see that `AnnIndex` has the same dimension of output with the estimated body_I/U/V. One thing puzzles me is that I wonder why the author named this variable as `AnnIndex` for part segmentation. At first I thought it was "Annotation Index".

**Comment by Johnqczhang** [comment]
> Thanks for your reply !
> But I am still puzzled. What do you mean by " the latter takes input as the former ".
> My understanding is that `AnnIndex` takes `AnnIndex_lowres` as input. But the output dim of `AnnIndex_loweres` is 15 but the input dim of `AnnIndex` is 25. That is what confuses me.

@penincillin Hi, I think [this line of code](https://github.com/facebookresearch/DensePose/blob/master/detectron/modeling/detector.py#L340) in the implementation of `BilinearInterpolation` can give you a hint on your confusion. You can see that [`BilinearInterpolation`](https://github.com/facebookresearch/DensePose/blob/master/detectron/modeling/detector.py#L361)  is actually implemented by [`ConvTranspose`](https://github.com/pytorch/pytorch/blob/master/caffe2/operators/conv_transpose_op.cc) in which the number of output channels is determined by the argument `dim_out` passed in `BilinearInterpolation` (see [GetOutputSize()](https://github.com/pytorch/pytorch/blob/master/caffe2/operators/conv_transpose_unpool_op_base.h#L134) of `ConvTranspose`).
