### ISSUE TITLE
make ops 

### ISSUE THREAD

**Issue by yyf8989** [facebookresearch/DensePose#204]
mkdir -p build && cd build && cmake .. && make -j12
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-9.0 (found version "9.0") 
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda-9.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-9.0
-- Caffe2: Header version is: 9.0
-- Found CUDNN: /usr/local/cuda-9.0/include  
-- Found cuDNN: v7.4.1  (include: /usr/local/cuda-9.0/include, library: /usr/local/cuda-9.0/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s): 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Summary:
--   CMake version        : 3.13.3
--   CMake command        : /home/yyf/.local/lib/python2.7/site-packages/cmake/data/bin/cmake
--   System name          : Linux
--   C++ compiler         : /usr/bin/c++
--   C++ compiler version : 4.9.4
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 1.0.0
--   Caffe2 include path  : /home/yyf/anaconda2/lib/python2.7/site-packages/torch/include
--   Caffe2 found CUDA    : True
--     CUDA version       : 9.0
--     CuDNN version      : 7.4.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yyf/DETECTRON/build
make[1]: Entering directory '/home/yyf/DETECTRON/build'
make[2]: Entering directory '/home/yyf/DETECTRON/build'
make[3]: Entering directory '/home/yyf/DETECTRON/build'
make[3]: Entering directory '/home/yyf/DETECTRON/build'
Scanning dependencies of target caffe2_detectron_custom_ops
[ 20%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o
make[3]: Leaving directory '/home/yyf/DETECTRON/build'
make[3]: Entering directory '/home/yyf/DETECTRON/build'
[ 40%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
In file included from /home/yyf/pytorch/caffe2/core/operator.h:1375:0,
                 from /home/yyf/DETECTRON/detectron/ops/zero_even_op.h:21,
                 from /home/yyf/DETECTRON/detectron/ops/zero_even_op.cc:17:
/home/yyf/pytorch/caffe2/core/c10_operator.h: In function ‘void caffe2::detail::_call_caffe2_op_from_c10(c10::Stack*, const c10::FunctionSchema&, c10::DeviceType, void (*)(const c10::FunctionSchema&, std::vector<c10::IValue, std::allocator<c10::IValue> >&, std::vector<c10::IValue*>&))’:
/home/yyf/pytorch/caffe2/core/c10_operator.h:40:53: error: ‘void outputs’ has incomplete type
   auto outputs = torch::jit::pop(*stack, num_outputs);
                                                     ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:41:51: error: ‘void inputs’ has incomplete type
   auto inputs = torch::jit::pop(*stack, num_inputs);
                                                   ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:45:23: error: unable to deduce ‘auto&&’ from ‘outputs’
   for (auto& output : outputs) {
                       ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:53:23: error: unable to deduce ‘auto&&’ from ‘outputs’
   for (auto& output : outputs) {
                       ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:59:22: error: unable to deduce ‘auto&&’ from ‘outputs’
   for (auto& output: outputs) {
                      ^
/home/yyf/pytorch/caffe2/core/c10_operator.h: At global scope:
/home/yyf/pytorch/caffe2/core/c10_operator.h:68:43: error: ‘OperatorHandle’ in namespace ‘c10’ does not name a type
 template<class Caffe2Operator> const c10::OperatorHandle& c10_op_handle_for_c2_op();
                                           ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:72:10: error: ‘c10::KernelCache’ has not been declared
     c10::KernelCache* cache) { // TODO Pass in correct cache type
          ^
/home/yyf/pytorch/caffe2/core/c10_operator.h: In function ‘void caffe2::detail::call_caffe2_op_from_c10(c10::Stack*, int*)’:
/home/yyf/pytorch/caffe2/core/c10_operator.h:75:7: error: ‘c10_op_handle_for_c2_op’ was not declared in this scope
       c10_op_handle_for_c2_op<Caffe2Operator>().schema(),
       ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:75:45: error: expected primary-expression before ‘>’ token
       c10_op_handle_for_c2_op<Caffe2Operator>().schema(),
                                             ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:75:47: error: expected primary-expression before ‘)’ token
       c10_op_handle_for_c2_op<Caffe2Operator>().schema(),
                                               ^
In file included from /home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/dispatch/OpSchema.h:10:0,
                 from /home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/dispatch/DispatchTable.h:3,
                 from /home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:3,
                 from /home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/dispatch/OpSchemaRegistration.h:3,
                 from /home/yyf/pytorch/caffe2/core/c10_operator.h:4,
                 from /home/yyf/pytorch/caffe2/core/operator.h:1375,
                 from /home/yyf/DETECTRON/detectron/ops/zero_even_op.h:21,
                 from /home/yyf/DETECTRON/detectron/ops/zero_even_op.cc:17:
/home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/stack.h: In instantiation of ‘void torch::jit::pop(torch::jit::Stack&, Types& ...) [with Types = const long unsigned int; torch::jit::Stack = std::vector<c10::IValue, std::allocator<c10::IValue> >]’:
/home/yyf/pytorch/caffe2/core/c10_operator.h:40:53:   required from here
/home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/stack.h:64:13: error: assignment of read-only reference ‘args#0’
       (args = std::move(peek(stack, i++, N)).template to<Types>(), 0)...};
             ^
CMakeFiles/caffe2_detectron_custom_ops.dir/build.make:62: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o] Error 1
make[3]: Leaving directory '/home/yyf/DETECTRON/build'
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make[2]: *** 正在等待未完成的任务....
Scanning dependencies of target caffe2_detectron_custom_ops_gpu
make[3]: Leaving directory '/home/yyf/DETECTRON/build'
make[3]: Entering directory '/home/yyf/DETECTRON/build'
[ 60%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/zero_even_op.cc.o
In file included from /home/yyf/pytorch/caffe2/core/operator.h:1375:0,
                 from /home/yyf/DETECTRON/detectron/ops/zero_even_op.h:21,
                 from /home/yyf/DETECTRON/detectron/ops/zero_even_op.cc:17:
/home/yyf/pytorch/caffe2/core/c10_operator.h: In function ‘void caffe2::detail::_call_caffe2_op_from_c10(c10::Stack*, const c10::FunctionSchema&, c10::DeviceType, void (*)(const c10::FunctionSchema&, std::vector<c10::IValue, std::allocator<c10::IValue> >&, std::vector<c10::IValue*>&))’:
/home/yyf/pytorch/caffe2/core/c10_operator.h:40:53: error: ‘void outputs’ has incomplete type
   auto outputs = torch::jit::pop(*stack, num_outputs);
                                                     ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:41:51: error: ‘void inputs’ has incomplete type
   auto inputs = torch::jit::pop(*stack, num_inputs);
                                                   ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:45:23: error: unable to deduce ‘auto&&’ from ‘outputs’
   for (auto& output : outputs) {
                       ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:53:23: error: unable to deduce ‘auto&&’ from ‘outputs’
   for (auto& output : outputs) {
                       ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:59:22: error: unable to deduce ‘auto&&’ from ‘outputs’
   for (auto& output: outputs) {
                      ^
/home/yyf/pytorch/caffe2/core/c10_operator.h: At global scope:
/home/yyf/pytorch/caffe2/core/c10_operator.h:68:43: error: ‘OperatorHandle’ in namespace ‘c10’ does not name a type
 template<class Caffe2Operator> const c10::OperatorHandle& c10_op_handle_for_c2_op();
                                           ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:72:10: error: ‘c10::KernelCache’ has not been declared
     c10::KernelCache* cache) { // TODO Pass in correct cache type
          ^
/home/yyf/pytorch/caffe2/core/c10_operator.h: In function ‘void caffe2::detail::call_caffe2_op_from_c10(c10::Stack*, int*)’:
/home/yyf/pytorch/caffe2/core/c10_operator.h:75:7: error: ‘c10_op_handle_for_c2_op’ was not declared in this scope
       c10_op_handle_for_c2_op<Caffe2Operator>().schema(),
       ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:75:45: error: expected primary-expression before ‘>’ token
       c10_op_handle_for_c2_op<Caffe2Operator>().schema(),
                                             ^
/home/yyf/pytorch/caffe2/core/c10_operator.h:75:47: error: expected primary-expression before ‘)’ token
       c10_op_handle_for_c2_op<Caffe2Operator>().schema(),
                                               ^
In file included from /home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/dispatch/OpSchema.h:10:0,
                 from /home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/dispatch/DispatchTable.h:3,
                 from /home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:3,
                 from /home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/dispatch/OpSchemaRegistration.h:3,
                 from /home/yyf/pytorch/caffe2/core/c10_operator.h:4,
                 from /home/yyf/pytorch/caffe2/core/operator.h:1375,
                 from /home/yyf/DETECTRON/detectron/ops/zero_even_op.h:21,
                 from /home/yyf/DETECTRON/detectron/ops/zero_even_op.cc:17:
/home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/stack.h: In instantiation of ‘void torch::jit::pop(torch::jit::Stack&, Types& ...) [with Types = const long unsigned int; torch::jit::Stack = std::vector<c10::IValue, std::allocator<c10::IValue> >]’:
/home/yyf/pytorch/caffe2/core/c10_operator.h:40:53:   required from here
/home/yyf/anaconda2/lib/python2.7/site-packages/torch/include/ATen/core/stack.h:64:13: error: assignment of read-only reference ‘args#0’
       (args = std::move(peek(stack, i++, N)).template to<Types>(), 0)...};
             ^
CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/build.make:69: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/zero_even_op.cc.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/zero_even_op.cc.o] Error 1
make[3]: Leaving directory '/home/yyf/DETECTRON/build'
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all] Error 2
make[2]: Leaving directory '/home/yyf/DETECTRON/build'
Makefile:129: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/yyf/DETECTRON/build'
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 2

**Comment by yyf8989** [comment]
is this GCC version problem?

**Comment by vkhalidov** [comment]
@yyf8989 No, this is a problem of desynchronization of ATen and the rest of PyTorch / Caffe2. Your ATen header `ATen/core/stack.h` corresponds to the version [before Feb 1, 2019](https://github.com/pytorch/pytorch/blob/dfb081a7e4d8cbef53084eb17968e837a825b248/aten/src/ATen/core/stack.h). At that point the file [caffe2/core/c10_operator.h](https://github.com/pytorch/pytorch/commits/master/caffe2/core/c10_operator.h) didn't even exist. See [this commit](https://github.com/pytorch/pytorch/commit/6750e1e3e995f2070464236d1585a772e647e524#diff-297aff332ad59abde8a9f92997805ee4) for further details.
You should clean up your installation and do a clean install PyTorch / Caffe2.

**Comment by yyf8989** [comment]
> @yyf8989 No, this is a problem of desynchronization of ATen and the rest of PyTorch / Caffe2. Your ATen header `ATen/core/stack.h` corresponds to the version [before Feb 1, 2019](https://github.com/pytorch/pytorch/blob/dfb081a7e4d8cbef53084eb17968e837a825b248/aten/src/ATen/core/stack.h). At that point the file [caffe2/core/c10_operator.h](https://github.com/pytorch/pytorch/commits/master/caffe2/core/c10_operator.h) didn't even exist. See [this commit](https://github.com/pytorch/pytorch/commit/6750e1e3e995f2070464236d1585a772e647e524#diff-297aff332ad59abde8a9f92997805ee4) for further details.
> You should clean up your installation and do a clean install PyTorch / Caffe2.

thanks very much!! I made it work by reinstalling the whole Pytoch /Caffe envs.
