### ISSUE TITLE
draw  the isocontours of the UV fields

### ISSUE THREAD

**Issue by CompliceU** [facebookresearch/DensePose#217]
i want to use opencv do this work,but i don't konw how to do it ,who can tell me ?~~~~ @rversaw @Celebio @Yangqing

**Comment by Johnqczhang** [comment]
Run `conda install opencv` or `pip install opencv-python`

**Comment by CompliceU** [comment]
hah,thx for your reply,but i want to use opencv  instead of matlotlib,i don't konw how to use it @Johnqczhang

**Comment by Johnqczhang** [comment]
Maybe this will help you: [OpenCV Contours](https://docs.opencv.org/3.4.2/d4/d73/tutorial_py_contours_begin.html)

**Comment by vkhalidov** [comment]
you can have a look in the visualization code for detectron2 DensePose [here](https://github.com/facebookresearch/detectron2/blob/4eb9dcabfc5f35dc2ee99c83e4c954ad7d97be02/projects/DensePose/densepose/vis/densepose.py#L120). This is a version of the [marching squares](https://en.wikipedia.org/wiki/Marching_squares) algorithm.
