### ISSUE TITLE
Core Dumped issue (K80 and M40)

### ISSUE THREAD

**Issue by yyf8989** [facebookresearch/DensePose#218]
> **### Here is my issue when i run python test_zero_even_op.py** 

(densepose) root@ycyy-gpu2:~/DensePose/detectron/tests# python test_zero_even_op.py 
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)

> `### **_below is my build history:_**`

(densepose) root@ycyy-gpu2:~/DensePose/build# make
Scanning dependencies of target caffe2_detectron_custom_ops
[ 12%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
[ 25%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
[ 37%] Linking CXX shared library libcaffe2_detectron_custom_ops.so
[ 37%] Built target caffe2_detectron_custom_ops
[ 50%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o
/root/anaconda3/envs/densepose/lib/python2.7/site-packages/torch/include/c10/util/ArrayRef.h:273:55: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
 using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
                                                       ^
[ 62%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o
/root/anaconda3/envs/densepose/lib/python2.7/site-packages/torch/include/c10/util/ArrayRef.h:273:55: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
 using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
                                                       ^
Scanning dependencies of target caffe2_detectron_custom_ops_gpu
[ 75%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/pool_points_interp.cc.o
[ 87%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/zero_even_op.cc.o
[100%] Linking CXX shared library libcaffe2_detectron_custom_ops_gpu.so
[100%] Built target caffe2_detectron_custom_ops_gpu

what's the problem?  Compile issue? I'm not good at C++/C, Is there anybody who can help solve this question ?  thanks in advance~
@linkinpark213

**Comment by yyf8989** [comment]
> > **### Here is my issue when i run python test_zero_even_op.py**
> 
> (densepose) root@ycyy-gpu2:~/DensePose/detectron/tests# python test_zero_even_op.py
> [E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
> [E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
> [E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
> terminate called after throwing an instance of 'std::system_error'
> what(): Invalid argument
> Aborted (core dumped)
> 
> > `### **_below is my build history:_**`
> 
> (densepose) root@ycyy-gpu2:~/DensePose/build# make
> Scanning dependencies of target caffe2_detectron_custom_ops
> [ 12%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
> [ 25%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
> [ 37%] Linking CXX shared library libcaffe2_detectron_custom_ops.so
> [ 37%] Built target caffe2_detectron_custom_ops
> [ 50%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o
> /root/anaconda3/envs/densepose/lib/python2.7/site-packages/torch/include/c10/util/ArrayRef.h:273:55: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
> using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
> ^
> [ 62%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o
> /root/anaconda3/envs/densepose/lib/python2.7/site-packages/torch/include/c10/util/ArrayRef.h:273:55: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
> using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
> ^
> Scanning dependencies of target caffe2_detectron_custom_ops_gpu
> [ 75%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/pool_points_interp.cc.o
> [ 87%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/zero_even_op.cc.o
> [100%] Linking CXX shared library libcaffe2_detectron_custom_ops_gpu.so
> [100%] Built target caffe2_detectron_custom_ops_gpu
> 
> what's the problem? Compile issue? I'm not good at C++/C, Is there anybody who can help solve this question ? thanks in advance~
> @linkinpark213

ps( I have run it successful in my  ubuntu16.04 envs (GPU  GTX 1060 ),but when i want to run it  on my GPU(K80) to see the improvement ,the problem happened!
envs:
ubuntu 18.04
gcc/g++ 4.8.5
protobuf =3.6.1

**Comment by yyf8989** [comment]
> > **### Here is my issue when i run python test_zero_even_op.py**
> 
> (densepose) root@ycyy-gpu2:~/DensePose/detectron/tests# python test_zero_even_op.py
> [E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
> [E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
> [E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
> terminate called after throwing an instance of 'std::system_error'
> what(): Invalid argument
> Aborted (core dumped)
> 
> > `### **_below is my build history:_**`
> 
> (densepose) root@ycyy-gpu2:~/DensePose/build# make
> Scanning dependencies of target caffe2_detectron_custom_ops
> [ 12%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
> [ 25%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
> [ 37%] Linking CXX shared library libcaffe2_detectron_custom_ops.so
> [ 37%] Built target caffe2_detectron_custom_ops
> [ 50%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o
> /root/anaconda3/envs/densepose/lib/python2.7/site-packages/torch/include/c10/util/ArrayRef.h:273:55: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
> using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
> ^
> [ 62%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o
> /root/anaconda3/envs/densepose/lib/python2.7/site-packages/torch/include/c10/util/ArrayRef.h:273:55: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
> using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
> ^
> Scanning dependencies of target caffe2_detectron_custom_ops_gpu
> [ 75%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/pool_points_interp.cc.o
> [ 87%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/zero_even_op.cc.o
> [100%] Linking CXX shared library libcaffe2_detectron_custom_ops_gpu.so
> [100%] Built target caffe2_detectron_custom_ops_gpu
> 
> what's the problem? Compile issue? I'm not good at C++/C, Is there anybody who can help solve this question ? thanks in advance~
> @linkinpark213

ps( I have run it successful in my  ubuntu16.04 envs (GPU  GTX 1060 ),but when i want to run it  on my GPU(K80) to see the improvement ,the problem happened!
envs:
ubuntu 18.04
gcc/g++ 4.8.5
protobuf =3.6.1
cmake: 3.8.2

**Comment by linkinpark213** [comment]
> what's the problem? Compile issue? I'm not good at C++/C, Is there anybody who can help solve this question ? thanks in advance~
> @linkinpark213

I'm sorry but I'm not a developer... I'll try to help as much as I can.

> /root/anaconda3/envs/densepose/lib/python2.7/site-packages/torch/include/c10/util/ArrayRef.h:273:55: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
^

I don't think the warning during your compiling is a problem - it's just a deprecated usage that hasn't been deleted for the sake of compatibility.

Some of my thoughts:
1. Are you sure that you are running it on GPU and that you got enough memory (both main memory and GPU memory)? I met with segmentation faults when running their MaskR-CNN Benchmark, and found that swapping for GPU resolved that.
2. Perhaps a thread synchronization issue? Maybe add these compiler flags in `CMakeLists.txt` of DensePose before compiling it?
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
```

**Comment by yyf8989** [comment]
> > what's the problem? Compile issue? I'm not good at C++/C, Is there anybody who can help solve this question ? thanks in advance~
> > @linkinpark213
> 
> I'm sorry but I'm not a developer... I'll try to help as much as I can.
> 
> > /root/anaconda3/envs/densepose/lib/python2.7/site-packages/torch/include/c10/util/ArrayRef.h:273:55: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
> > using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
> > ^
> 
> I don't think the warning during your compiling is a problem - it's just a deprecated usage that hasn't been deleted for the sake of compatibility.
> 
> Some of my thoughts:
> 
>     1. Are you sure that you are running it on GPU and that you got enough memory (both main memory and GPU memory)? I met with segmentation faults when running their MaskR-CNN Benchmark, and found that swapping for GPU resolved that.
> 
>     2. Perhaps a thread synchronization issue? Maybe add these compiler flags in `CMakeLists.txt` of DensePose before compiling it?
> 
> 
> ```
> set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread")
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
> ```

thanks for your reply ！
I tried your advise, but it still have the core dumped or get stuck .
Thank you all the same for your help~ 
![图片](https://user-images.githubusercontent.com/43921609/54585805-1c108b80-4a56-11e9-85c1-13b79f5cd52c.png)

**Comment by Johnqczhang** [comment]
@yyf8989 Try rolling back your protobuf to an older version. See [this issue](https://github.com/protocolbuffers/protobuf/issues/4958).

**Comment by yyf8989** [comment]
> @yyf8989 Try rolling back your protobuf to an older version. See [this issue](https://github.com/protocolbuffers/protobuf/issues/4958).

thanks for your help, I've solved my problem by changing my envs.
sys: Centos 7.x
gcc 4.8.5 --> 4.9.2
protobuf 3.6.1 --> 3.5.0
