### ISSUE TITLE
What's the correspondence between these twenty four part and the human body

### ISSUE THREAD

**Issue by l1346792580123** [facebookresearch/DensePose#220]
![untitled](https://user-images.githubusercontent.com/25956606/54738347-d5a26480-4bee-11e9-922a-1d2b20478308.png
Hi this picture is obtained from UV_Processed.mat, but I really hope to know the correspondence between each part and the human body. Specifically I hope to know each part  belongs to left or right side and front or back of the human body.  Does anybody know ?

**Comment by Johnqczhang** [comment]
You can visualize all points on the SMPL model by leveraging helpful functions in [DensePose-COCO-on-SMPL.ipynb](https://github.com/facebookresearch/DensePose/blob/master/notebooks/DensePose-COCO-on-SMPL.ipynb), as shown in the image below
![SMPL_collected_UVpoints](https://user-images.githubusercontent.com/7107859/54797179-11d8d200-4c8e-11e9-822b-9b6b40d28283.png)

**Comment by l1346792580123** [comment]
Thank you very much  it helps a lot
