### ISSUE TITLE
'Non-existent config key: MODEL.BODY_UV_ON'

### ISSUE THREAD

**Issue by zsw667291** [facebookresearch/DensePose#226]
hi all！
I installed the densepose & caffe2 & detectron.when i run the code. i receive the following code:

`$ python  tools/infer_simple.py \
>     --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml \
>     --output-dir DensePoseData/infer_out/ \
>     --image-ext jpg \
>     --wts https://dl.fbaipublicfiles.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl \
>     DensePoseData/demo_data/demo_im.jpg
Found Detectron ops lib: /home/SENSETIME/zhushiwei/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2_detectron_ops_gpu.so
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Traceback (most recent call last):
  File "tools/infer_simple.py", line 140, in <module>
    main(args)
  File "tools/infer_simple.py", line 87, in main
    merge_cfg_from_file(args.cfg)
  File "/home/SENSETIME/zhushiwei/sense_work/detectron/detectron/core/config.py", line 1147, in merge_cfg_from_file
    _merge_a_into_b(yaml_cfg, __C)
  File "/home/SENSETIME/zhushiwei/sense_work/detectron/detectron/core/config.py", line 1207, in _merge_a_into_b
    _merge_a_into_b(v, b[k], stack=stack_push)
  File "/home/SENSETIME/zhushiwei/sense_work/detectron/detectron/core/config.py", line 1197, in _merge_a_into_b
    raise KeyError('Non-existent config key: {}'.format(full_key))
KeyError: 'Non-existent config key: MODEL.BODY_UV_ON'
`
how can i fix this?

**Comment by usrFabian** [comment]
Hi @zsw667291,
how did you solve this problem? I'm getting the same error.
Best
Fabian
