### ISSUE TITLE
Where could I download "demo_dp_single_ann.pkl"?

### ISSUE THREAD

**Issue by utc1205** [facebookresearch/DensePose#26]
when I run DensePose-COCO-on-SMPL.ipynb, I found the file (demo_dp_single_ann.pkl) is missing,
so where i can download the pkl ? Thanks

**Comment by benlee12** [comment]
guess can be produced by densepose main program? miss it too.

**Comment by ralpguler** [comment]
`demo_dp_single_ann.pkl` added.  

Thanks for reporting!

**Comment by ingramator** [comment]
How do you generate this file?
