### ISSUE TITLE
Finding the nose using Densepose

### ISSUE THREAD

**Issue by sagilehman** [facebookresearch/DensePose#263]
Hi,
I want to find the nose of a human in a given picture. In order to do this I'm using Densepose to create a 3d model of the human, which I then transform to a 2d model on Z and Y axes. I tried to find the nose by detecting the peaks of the body, but there are a lot of little peaks along the way, so I can't find the specific peak which represents the nose.
Do you have an idea for how I may find the nose in the model?
Thanks in advance

**Comment by vkhalidov** [comment]
Hello @sagilehman, you can have a look at the charts [here](https://github.com/facebookresearch/DensePose/blob/master/notebooks/DensePose-RCNN-Texture-Transfer.ipynb) and use the corresponding labels (23, 24) and UV coordinates to determine nose location. Alternatively, you can try to use the [keypoints model](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#keypoint-detection-baselines) to locate nose
