### ISSUE TITLE
Estimate human body measurements using DensePose - 3D coordinates

### ISSUE THREAD

**Issue by zimratK** [facebookresearch/DensePose#267]
Hi,
I am trying to solve the following problem I have when using DensePose: 
Given one image of a patient laying on a hospital bed, we aim to calculate his or her height.
I know the measurements of the bed, and the coordinates of the corners of the bed on the image. 
I would like to reconstruct a 3D model of the patient using DensePose, and to use this to calculate the distances between points on the body and  the surface of the bed. I have the IUV images, but I want to get the XYZ coordinates of the patient. I tried to create a coverage on an SMPL model(to 'wrap' an SMPL model with the 2d result of the IUV coordinates), but by doing this I didn’t get the real pose of him/her, and I didn't get the right measurements.

![image](https://user-images.githubusercontent.com/46006914/76705028-a7fad900-66e5-11ea-9e37-fc09c797bbf6.png)

Is there a way I can get 3D points of the human body from the IUV coordinates?
Thanks in advance,
Zimrat

**Comment by vkhalidov** [comment]
DensePose produces mappings onto a generic surface, it is therefore not directly suitable for 3D reconstruction.
