### ISSUE TITLE
UV_Processed.mat

### ISSUE THREAD

**Issue by patodichayan** [facebookresearch/DensePose#281]
How do you generate the UV_Processed.mat and UV_symmetry_transforms.mat ?! 
What if I use the Smpl-x model, do those files remain the same for that model, or does it change?!

**Comment by patodichayan** [comment]
@vkhalidov Please let me know the steps to generate that .mat file for a newer SMPL-x model.

**Comment by vkhalidov** [comment]
@patodichayan the key is to define the split into charts, as shown below:
<img src="http://densepose.org/img/coords.png" width="400px" />

If you've got a different mesh, you'll need to map that mesh to the original one, recompute part labels and U and V coordinates for each vertex of the new mesh. This is what is stored in `UV_Processed.mat`.
Symmetry transforms can be generated from `UV_Processed.mat` with the help of vertex correspondences under the symmetry transform.

**Comment by patodichayan** [comment]
@vkhalidov Thank you so much. 
Do you have a script that does this somewhere in the code? or If you can provide me with the script that you used, it would be much appreciated.

Thanks.

**Comment by vkhalidov** [comment]
it was @ralpguler who defined the charts in the first place. The scripts are not available in the DensePose code. However, if you establish correspondences between the meshes, you can define similar UV coordinates for your mesh.
