### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by alexbw** [facebookresearch/DensePose#29]
Hello, the paper was super interesting! Really glad you open sourced your work.
The LICENSE file clearly indicates the code released here is usable for non-commercial work only. However, it's unclear if this license extends to the dataset that is also released here. Could you clarify?

**Comment by vkhalidov** [comment]
The licensing information was added to the [DensePose](http://densepose.org/) page:
> DensePose-COCO and DensePose-PoseTrack datasets are distributed under [NonCommercial Creative Commons](https://creativecommons.org/licenses/by-nc/2.0/) license.
