### ISSUE TITLE
KeyError: u'Non-existent config key: BODY_UV_RCNN'

### ISSUE THREAD

**Issue by peancor** [facebookresearch/DensePose#33]
Hello,
The tests in the install section are passing OK and i have downloaded the DenseposeData but when i try to do inference as proposed in the getting started:

`python2 tools/infer_simple.py \
    --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml \
    --output-dir DensePoseData/infer_out/ \
    --image-ext jpg \
    --wts https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl \
    DensePoseData/demo_data/demo_im.jpg`

i got the following error:
`Traceback (most recent call last):
  File "tools/infer_simple.py", line 140, in <module>
    main(args)
  File "tools/infer_simple.py", line 87, in main
    merge_cfg_from_file(args.cfg)
  File "/home/user/densepose/detectron/detectron/core/config.py", line 1127, in merge_cfg_from_file
    _merge_a_into_b(yaml_cfg, __C)
  File "/home/user/densepose/detectron/detectron/core/config.py", line 1177, in _merge_a_into_b
    raise KeyError('Non-existent config key: {}'.format(full_key))
KeyError: u'Non-existent config key: BODY_UV_RCNN'
`
Thank you in advance.

**Comment by vkhalidov** [comment]
It seems like you have a separate installation of `detectron` library in your `densepose/detectron` folder. You should avoid mixing different libraries. Try clean install of DensePose.

**Comment by peancor** [comment]
solved!, thank you!
Kind regards.

**Comment by pkishan1990** [comment]
hello, 
I am facing same issue, could  you please explain how you solved
