### ISSUE TITLE
Example models with keypoint detection?

### ISSUE THREAD

**Issue by lambdaloop** [facebookresearch/DensePose#34]
I'm wondering how I should setup the model in order to get keypoints?
It seems that none of the example files in configs have `MODEL.KEYPOINTS_ON = True`.
Any suggestions? Are there any pretrained models which also generate keypoints?

Thank you!

**Comment by vkhalidov** [comment]
Please check the keypoint model configurations in [Detectron](https://github.com/facebookresearch/Detectron) repository (e.g. [e2e_keypoint_rcnn_R-101-FPN_s1x](https://github.com/facebookresearch/Detectron/blob/master/configs/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml))

**Comment by AlexLuya** [comment]
@vkhalidov 
Do you mean we need to train new model to support keypoints detection

**Comment by minthetkhine** [comment]
Is it feasible to train such a model on only 1 GPU? Currently, this has always led to "run out of memory".
