### ISSUE TITLE
load "demo_dp_single_ann.pkl" error

### ISSUE THREAD

**Issue by LimingYin** [facebookresearch/DensePose#36]
pkl_file = open('DensePoseData/demo_data/demo_dp_single_ann.pkl', 'rb')
Demo = pickle.load(pkl_file)    

error:
    dispatch [key] (self)
KeyError: '\n'

**Comment by vkhalidov** [comment]
please check the md5 sum of the file, it should be `c4790e4ebde6dd0c312964d6a36d15d8`
