### ISSUE TITLE
3d Reconstruction/Triangulation

### ISSUE THREAD

**Issue by shadow111** [facebookresearch/DensePose#40]
is it possible to output a 3d model(mesh ) using image as input??
Thank you

**Comment by danache** [comment]
[](https://github.com/facebookresearch/DensePose/blob/master/notebooks/DensePose-COCO-on-SMPL.ipynb)
This page may help you?

**Comment by shadow111** [comment]
Thank you so much

**Comment by ingramator** [comment]
How do you do it for an arbritary image though?
