### ISSUE TITLE
'ascii' codec can't decode byte 0x81 in position 1224: ordinal not in range(128)

### ISSUE THREAD

**Issue by inkplay** [facebookresearch/DensePose#42]
Following the DensePose-COCO dataset and SMPL model notebook and after I downloaded and extracted the file in the correct location I get this error.

`---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-5702eecc3ed1> in <module>()
      6 # Now read the smpl model.
      7 with open('../DensePoseData/basicmodel_m_lbs_10_207_0_v1.0.0.pkl', 'rb') as f:
----> 8     data = pickle.load(f)
      9     Vertices = data['v_template']  ##  Loaded vertices of size (6890, 3)
     10     X,Y,Z = [Vertices[:,0], Vertices[:,1],Vertices[:,2]]

UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 1224: ordinal not in range(128)`

**Comment by vkhalidov** [comment]
seems like you're trying to open Python 2 pickle from Python 3. Note that DensePose is meant to be used with Python 2 (see [DensePose/INSTALL.md](https://github.com/facebookresearch/DensePose/blob/master/INSTALL.md))

**Comment by jiapei100** [comment]
When will DensePose be **Python3** compatible?

**Comment by RSKothari** [comment]
To anyone who stumbles upon this in the future, this [comment](https://github.com/facebookresearch/DensePose/issues/142#issuecomment-435645312) solved the issue with Python 2 SMPL models.

**Comment by vkhalidov** [comment]
FYI: DensePose moved to detectron2 and is now available as a project there:
https://github.com/facebookresearch/detectron2/tree/master/projects/DensePose
It provides better and more diverse [baselines](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/doc/MODEL_ZOO.md) and is regularly updated with state-of-the-art methods ([uncertainty estimation](https://papers.nips.cc/paper/8378-correlated-uncertainty-for-learning-dense-correspondences-from-noisy-labels.pdf), [DensePose Evolution](https://openaccess.thecvf.com/content_CVPR_2020/html/Sanakoyeu_Transferring_Dense_Pose_to_Proximal_Animal_Classes_CVPR_2020_paper.html) pipeline etc.)

**Comment by RSKothari** [comment]
Thanks @vkhalidov , I managed to get detectron2 working. I'm particularly interested in getting it working with SMPL. However, I'm observing that the mapping between detected IUV coordinates and SMPL 1.0 model seem off. I'll raise a ticket after I've explored this a bit further.

**Comment by vkhalidov** [comment]
@RSKothari replied to you under the [corresponding issue](https://github.com/facebookresearch/detectron2/issues/1342) in detectron2
