### ISSUE TITLE
Cannot load Pdist_matrix due to MemoryError

### ISSUE THREAD

**Issue by phraust1612** [facebookresearch/DensePose#47]
Hi, currently I'm using a GCP VM instance of 
- 2 CPU, 8GB
- NVIDIA Tesla P100
but when I try test script below, which is given from "GETTING_STARTED.md", MemoryError occurs
```
python2 tools/test_net.py \  
    --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml \  
    TEST.WEIGHTS https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl \  
    NUM_GPUS 1
```

The error occured from _loadGEval() in detectron/datasets/densepose_cocoeval.py
```
f = h5py.File( prefix + 'Pdist_matrix.mat')  
for k, v in f.items():  
    arrays[k] = np.array(v)
```
Could you please help on this problem? Or do I need more larger memory device? Isn't 12GB of P100 large enough?

**Comment by vkhalidov** [comment]
Your error is not related to GPU memory, but rather normal RAM. Please note that in  [densepose_cocoeval.py](https://github.com/facebookresearch/DensePose/blob/master/detectron/datasets/densepose_cocoeval.py#L122) on lines 120-124, the file `Pdist_matrix.mat` of size 1.3 GB is read. This results in process memory print increase of around 3.65 GB. You should ensure you have enough free RAM.
