### ISSUE TITLE
Keypoint estimation

### ISSUE THREAD

**Issue by javierfuenca** [facebookresearch/DensePose#48]
I would like to know how I can generate an output for keypoint estimation. I know I have to make a config file setting `KEYPOINTS_ON: True` and adding the propper `KRCNN: ...`. But my question is: is there a model in the model zoo or anywhere already trained to do this or do I have to train mine? And in that case, which model should I train?

**Comment by vkhalidov** [comment]
We do not provide any pretrained model that would combine several heads (bodyuv, keypoints, mask etc). So if you want to obtain a model that uses a single backbone and several heads, you should train it yourself. For that you can combine configuration files from [DensePose](https://github.com/facebookresearch/DensePose/tree/master/configs) and [Detectron](https://github.com/facebookresearch/Detectron/tree/master/configs/12_2017_baselines) repositories. To decide which model to train, you need to formulate your needs in terms of inference time and precision and check the stats on Model Zoo pages for [DensePose](https://github.com/facebookresearch/DensePose/blob/master/MODEL_ZOO.md) and [Detectron](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md)
