### ISSUE TITLE
Can I  estimate 3D pose using densepose?

### ISSUE THREAD

**Issue by heury** [facebookresearch/DensePose#49]
Densepose can match each pixel to human body. 
So, I wonder if human body also can be matched to the original image in inverse.
Can I do that with densepose?

**Comment by vkhalidov** [comment]
related to #40 
Please check [DensePose-COCO-on-SMPL.ipynb](https://github.com/facebookresearch/DensePose/blob/master/notebooks/DensePose-COCO-on-SMPL.ipynb) notebook
