### ISSUE TITLE
how to process batch of images with tools/infer_simple.py?

### ISSUE THREAD

**Issue by BeginnerW** [facebookresearch/DensePose#51]
Does anybody know that? I'm a newcomer to caffe2.
Thx!

**Comment by vkhalidov** [comment]
you can put all your images into the same folder, set `--im_or_folder` argument to the folder and specify `--image-ext` if your images have an extension other than `jpg`

**Comment by BeginnerW** [comment]
@vkhalidov I guess the method you mentioned process images one by one instead of in parallel way . 
am i misunderstanding something, here is the script.
Anyway,Thx!

for i, im_name in enumerate(im_list):
        out_name = os.path.join(
            args.output_dir, '{}'.format(os.path.basename(im_name) + '.pdf')
        )
        logger.info('Processing {} -> {}'.format(im_name, out_name))
        im = cv2.imread(im_name)
        timers = defaultdict(Timer)
        t = time.time()
        with c2_utils.NamedCudaScope(0):
            cls_boxes, cls_segms, cls_keyps, cls_bodys = infer_engine.im_detect_all(
                model, im, None, timers=timers
            )

**Comment by vkhalidov** [comment]
Yes, this code resembles lines 99-110 of [infer_simple.py](https://github.com/facebookresearch/DensePose/blob/master/tools/infer_simple.py) and processes a sequence of images one by one. To parallelize the processing you'll need to check how this is [typically done in Caffe2](https://github.com/caffe2/tutorials/blob/master/Multi-GPU_Training.ipynb)

**Comment by BeginnerW** [comment]
Could  you provide me a demo script that do the some things like infer_simple.py but in parallel way? 
THANKS!

**Comment by BeginnerW** [comment]
Ok, i guess it is complicated. Maybe some similar script still can help me a lot. By the way, i am really newcomer, this is the second day with caffe2.
Thank you!

**Comment by BeginnerW** [comment]
@vkhalidov 
I am confused about the intermediate result i get like below. I hope you can give me a hint.
The problems is that i get the same numpy array shape of **rois** under different shape of **inputs**['data']. The origin shape of **inputs**['data'] in infer_simply.py is (1, 3, 736, 1344), but i concate two similar images to obtain **inputs**['data'] with shape of (2, 3, 736, 1344). The result is correct, however i loss 500 boxes per images. 

The reason why i am doing this is that i want images be processed in parallel way. Thanks!

    **inputs**, im_scale = _get_blobs(im, boxes, target_scale, target_max_size)
    for k, v in inputs.items():
        workspace.FeedBlob(core.ScopedName(k), v)
    workspace.RunNet(model.net.Proto().name)
    # Read out blobs
    if cfg.MODEL.FASTER_RCNN:
        **rois** = workspace.FetchBlob(core.ScopedName('rois'))
        # unscale back to raw image space rois.shape = (1000,5)
        boxes = rois[:, 1:5] / im_scale
