### ISSUE TITLE
Docker image is missing chumpy

### ISSUE THREAD

**Issue by Quasimondo** [facebookresearch/DensePose#52]
When testing the DensePose-COCO-on-SMPL notebook on the currently provided Docker image an "no module chumpy.ch found" error occurs when trying to load the SMPL model. This can be easily fixed by running pip install chumpy inside the Docker image, but it might be a good idea to add that install to the Dockerfile.

**Comment by ralpguler** [comment]
Chumpy is not a dependency, as we only use the template mesh of the SMPL model.

**Comment by Quasimondo** [comment]
Well, but for some reason when trying to load that template pickle an error is thrown.

**Comment by maxteleg** [comment]
Same error here. When I use 'DensePose-COCO-on-SMPL' notebook and try to visualize the smpl model, an error occurs: 'No module named chumpy.ch' which originally caused by executing pickle.load('SMPL_model_file')

**Comment by weigq** [comment]
+1

**Comment by kerrywang** [comment]
you need to also install chumpy

**Comment by davidleejy** [comment]
Had the same issue.  For those who have trouble installing chumpy (failed to install chumpy in a conda environment), here's an alternative to get chumpy working for you.

1. Git clone the chumpy repo (https://github.com/mattloper/chumpy).

2. Soft-link / copy the "chumpy" dir containing __init__.py, api_compatibility.py, etc.. into the dir containing code that calls `pickle.load(___)` .

An example:
```
│
├── notebooks
        ├── DensePose-COCO-on-SMPL.ipynb
        ├── chumpy
                 ├── api_compatibility.py
                 ├── ch_ops.py
                 ├── ch_ops.pyc
                 ├── ch.py
                 ├── ch.pyc
                    ...
```

**Comment by jaggernaut07** [comment]
pip install chumpy also should work
