### ISSUE TITLE
output 2D/3D coordinates for 6890 vertices in SMPL

### ISSUE THREAD

**Issue by penincillin** [facebookresearch/DensePose#55]
Thanks for making this tremendous work public available!
I have read the code of tools/infer_simple.py and the output of is UV coordinate. But I am more interested in the estimate SMPL model and I am wondering is it possible to output the 2D coordinates of the 6890 vertices given an image?

**Comment by nvrv** [comment]
@penincillin, this is not implemented. The most straightforward way to obtain the 2D coordinates is to fit the SMPL model into the DensePose predictions. https://github.com/classner/up could you be your starting point.

**Comment by penincillin** [comment]
Thanks a lot!

**Comment by ypflll** [comment]
@penincillin I also want to get SMPL vertices. Any progress?

**Comment by ypflll** [comment]
@ingramator UP or SMPLify fits SMPL para using 2d key points, which I think can be used here.
Or this one: https://akanazawa.github.io/hmr/

But they all can't be used directly.

**Comment by ingramator** [comment]
@ypflll they both use 2d key points to fit the model and the range of 2d keypoints is always yields very poor performance, particularly for regions like the feet which in almost every pose estimation framework have no labels. This makes for embarassingly poor model predictions, the predictions made by densepose however are very strong even without model fitting! Do you have any suggestions for how we can go about doing this

**Comment by ypflll** [comment]
@ingramator How about using output of densepose(only visiable points) to fit the model?

**Comment by ypflll** [comment]
@ingramator Any progress? I am starting to do this now.

**Comment by ingramator** [comment]
@ypflll No progress yet because the accuracies of the dense correspondences are far too muddy. I think the best bet is using the 2D keypoints in the detectron outputs. I will publish my findings in a couple of weeks!

Have u made any progress?

**Comment by AnirudhPuligandla** [comment]
Hello @ingramator . I am also interested in fitting an SMPL model onto the densepose outputs. Do you have any leads?

**Comment by ypflll** [comment]
@AnirudhPuligandla This may help you: https://arxiv.org/pdf/1811.11459.pdf

**Comment by AnirudhPuligandla** [comment]
@ypflll Thanks for your reply. The went through that paper but they deal more about texture. I think I will try to use [this](https://github.com/akanazawa/hmr) for my project as i more interested in 3D mesh at the moment. Thanks.

**Comment by jaggernaut007** [comment]
Thanks. It's above paper

**Comment by ayjabia** [comment]
I was able to plot the skeleton according to joints3d. How can I project it onto the original image?
When projecting onto the z axis, I get a slightly rotated skeleton relative to the image.

**Comment by wine3603** [comment]
Did anyone find the way to output 3D coordinate of the 6890 vertex?
