### ISSUE TITLE
Infer to a video

### ISSUE THREAD

**Issue by albertchristianto** [facebookresearch/DensePose#60]
Hi,
Thank you for your great work. My name is Albert Christianto.
I'm a little bit curious. Do you have any example code to infer a video ?
Thanks a lot.
best regards,
Albert

**Comment by vkhalidov** [comment]
You can extract individual images from a video, put them into a folder and run the [infer_simple.py](https://github.com/facebookresearch/DensePose/blob/master/tools/infer_simple.py) script

**Comment by vkhalidov** [comment]
related to #18 , #51

**Comment by savankoradiya** [comment]
For video https://github.com/trrahul/densepose-video

**Comment by albertchristianto** [comment]
Thanks a lot for the response @vkhalidov  @savankoradiya.
I have modified the code so i can be able to infer a video.
But the fps can't put up, I am only get 3 fps in 640x480 video and around 6 fps in 320x180 video.
Could you give some tips to get same speed in the paper?

**Comment by ingramator** [comment]
@albertchristianto what GPU and what model are you using? The resnet50 model is the quickest for inference and if you are using the default inference code it is not optimised at all so it's not surprising you are getting that fps. 

If you want to get even faster speed but poorer results it should be possible to train the model using a lighter architecture like mobile or squeeze net.

**Comment by ipengx1029** [comment]
> Thanks a lot for the response @vkhalidov @savankoradiya.
> I have modified the code so i can be able to infer a video.
> But the fps can't put up, I am only get 3 fps in 640x480 video and around 6 fps in 320x180 video.
> Could you give some tips to get same speed in the paper?

hi，I'm a beginner of cv, I have tried some method to modify the code to infer a video, but I failed. Could you share your code with me. It would be appreciated if you could help me. Thank you!
