### ISSUE TITLE
text labels of body part indices

### ISSUE THREAD

**Issue by Ali2500** [facebookresearch/DensePose#64]
From what I understand the I-channel of the IUV image contains values in the range 1-25 corresponding to the body part/geometry. Is there a labeling for which part each value corresponds to? Like a text string like "upper left leg", "torso front".

**Comment by vkhalidov** [comment]
To understand the mapping, the best would be to apply a different color to every part and check the results. You can use [texture transfer](https://github.com/facebookresearch/DensePose/blob/master/notebooks/DensePose-RCNN-Texture-Transfer.ipynb) or [coloring](https://github.com/facebookresearch/DensePose/blob/master/notebooks/DensePose-COCO-Visualize.ipynb).

Below are human readable labels:
```
0      = Background
1, 2   = Torso
3      = Right Hand
4      = Left Hand
5      = Right Foot
6      = Left Foot
7, 9   = Upper Leg Right
8, 10  = Upper Leg Left
11, 13 = Lower Leg Right
12, 14 = Lower Leg Left
15, 17 = Upper Arm Left
16, 18 = Upper Arm Right
19, 21 = Lower Arm Left
20, 22 = Lower Arm Right
23, 24 = Head
```

**Comment by abhaydoke09** [comment]
Small question : For head, what's the difference between 23 and 24? Does 23 mean front of the head and 24 is back of the head?
