### ISSUE TITLE
demo_dp_single_ann.pkl

### ISSUE THREAD

**Issue by minhpvo** [facebookresearch/DensePose#65]
What is the conversion between 'U', 'V'  in the demo_dp_single_ann.pkl file and the 'uv' in the *_iuv.png file? From my understanding, 'U' 'V' in the *pkl file is in some normalized coordinates of the  'uv' in the *iuv.png

**Comment by vkhalidov** [comment]
Coordinates in the `_IUV.png` file are scaled by a factor of 255, please check how this file is generated [here](https://github.com/facebookresearch/DensePose/blob/master/detectron/utils/vis.py#L405)
