### ISSUE TITLE
I have one question about densepose result!

### ISSUE THREAD

**Issue by yagee97** [facebookresearch/DensePose#74]
I succeeded densepose test for video with reference to (https://github.com/trrahul/densepose-video).
while tests, i got a question. 

**1. When I detect an object using densepose, where are the keypoints' coordination stored? 
(which variable?)
Example) get_keypoints() in keypoints.py ?
2. What information can I use in densepose data?**

Thank you! i want to your detail opinion.

**Comment by lushihan** [comment]
Same question here

**Comment by yagee97** [comment]
@lushihan where..? sorry..

**Comment by yagee97** [comment]
@lushihan oh... i got it now.. i want to solve this question.

**Comment by lushihan** [comment]
Still no authors response :(

**Comment by vkhalidov** [comment]
@yagee97 To get keypoints, you need to train the model with the keypoints head. Please have a look at #34, #39, #48

**Comment by yagee97** [comment]
@vkhalidov Thank you!:) I understand your opinion! i'm so happy.
now, i'm trying to train keypoints. but i got an error. 

`RuntimeError: [enforce fail at blob.h:84] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/fpn_inner_res2_2_sum_lateral_w.
Error from operator: 
input: "gpu_0/res2_2_sum" input: "gpu_0/fpn_inner_res2_2_sum_lateral_w" input: "gpu_0/fpn_inner_res2_2_sum_lateral_b" output: "gpu_0/fpn_inner_res2_2_sum_lateral" name: "" type: "Conv" arg { name: "kernel" i: 1 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 0 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
`
<br>
use command 
`python2 ~/densepose/tools/infer_simple.py --cfg ~/densepose/configs/e2e_keypoint_rcnn_R-50-FPN_1x.yaml --output-dir DensePoseData/infer_out/ --image-ext jpg --wts https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl ~/d.jpg`

**what this error? Thank you for your reply**

**Comment by yagee97** [comment]
Thank you for your reply!
I have question one more. 

**What information can I use in densepose data?
I want to get some coordinate such as All_Coords in vis.py**

because I'm going to utilize person's 2d/3d coordinate at densepose result.

How I get 2D/3D coordinate? Where? 

Thank you! :) Have a good day!

**Comment by vkhalidov** [comment]
The output of the DensePose head is generated [here](https://github.com/facebookresearch/DensePose/blob/master/detectron/core/test.py#L889). You can see that for every detected person bounding box of size `(H, W)`, you [get the output](https://github.com/facebookresearch/DensePose/blob/master/detectron/core/test.py#L953) of size `(3, H, W)`. The first channel contains part index, the other 2 channels contain regressed inner coordinate values `U` and `V` for the corresponding part. Thus 2D image coordinates are obtained from bounding box coordinates + pixel offset within the bounding box. To understand how to map the estimated `IUV` values to the 3D SMPL models, please have a look at [DensePose-COCO-on-SMPL.ipynb](https://github.com/facebookresearch/DensePose/blob/master/notebooks/DensePose-COCO-on-SMPL.ipynb) notebook

**Comment by yagee97** [comment]
oh really thank you.! i'v got it this problem. So let me ask you one last question.
I want to store the `im_detect_body_uv` result. 
so I have tried to print its output. but print result is [0,0,0,0, .....] ! 

**How can I print or store them separately?**

very thank you for your kind! :)

**Comment by vkhalidov** [comment]
There are many possibilities to store results, for example [pickle](https://docs.python.org/2/library/pickle.html), [numpy](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.save.html), [json](https://docs.python.org/2/library/json.html).

For visualization, I suggest you to check [visualization](https://github.com/facebookresearch/DensePose/blob/master/notebooks/DensePose-RCNN-Visualize-Results.ipynb) and [texture transfer](https://github.com/facebookresearch/DensePose/blob/master/notebooks/DensePose-RCNN-Texture-Transfer.ipynb) notebooks

**Comment by anweiwei** [comment]
I want to use my own image to generate I,U,V and to visualize on the SMPL mode. Then I got the IUV output [3,H,W]. and the output[0], output[1] ,output[2]  is correspondent to I,U,V respectively. However, when I reference the  DensePose-COCO-on-SMPL.ipynb, in the demo_dp_single_ann.pkl, where I,U,V is a vector(length 125). So, my question is  how can I use the output[3,H,W] to do the visualization, or can you provide the code to generate the 
demo_dp_single_ann.pkl?

**Comment by jae251** [comment]
As far as I can tell you need to divide by 255. to use densepose_methods.IUV2FBC:

   FaceIndex,bc1,bc2,bc3=densepose_methods.IUV2FBC(output[0,i,j],output[1,i,j]/255.,output[2,i,j]/255.)

where you would iterate i and j over your image dimensions, just like in DensePose-COCO-on-SMPL.ipynb.

**Comment by ingramator** [comment]
Same question as anweiwei, how do we generate that demo_dp_single_ann.pkl file or do the visualisation given the IUV output for an arbritary object

**Comment by jaggernaut007** [comment]
@ingramator Did you manage to get the xyz from iuv output? do share your code. maybe we can collab and find a fix? I have the IUV output from the model. Cant make sense of it.

**Comment by ingramator** [comment]
@jaggernaut007 I have this working now are you still interested in seeing it?

**Comment by kalyo-zjl** [comment]
@ingramator Hi, how do you make it working? My IUV output from infer_simple.py doesn't seem to fit well when mapping it to the SMPL model. Could you please share the script?

**Comment by kekedan** [comment]
> Does anyone have any ideas

the same problem , so do you   any ideas?

**Comment by wine3603** [comment]
Hi guys, I am following the notebook of [https://github.com/facebookresearch/DensePose/pull/99](url)
but I cannot show the points on the smpl, the points on the picked person is always (0, 3), with pick_idx=1.
Does it work well in your cases?
