### ISSUE TITLE
Get Keypoints Coordinate

### ISSUE THREAD

**Issue by darasy** [facebookresearch/DensePose#77]
Hi, 
First, I’d like to thank for this amazing work.

I am currently trying to get the 3-D coordinates of each key points. I have tried to configure the model using the model from detection as you suggested in other issues. However, I always get an error. I wonder if you could provide the model with the Keypoints detection only? Also, how do I access the coordinates of each joint?

I would like to thank you beforehand for your response.

**Comment by yagee97** [comment]
me 2 :)

**Comment by vkhalidov** [comment]
Please have a look at Detectron models to estimate [keypoints](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#keypoint-detection-baselines). What is the error that you get when trying to run a model from Detectron?

**Comment by darasy** [comment]
I guess my problem was because I did not train the model. I did not exactly remember the error message that I receive as I have not test it further any longer, but it is something related to body_uv as I replace it with KEYPOINT.
