### ISSUE TITLE
UserWarning: No contour levels were found within the data range.

### ISSUE THREAD

**Issue by BryanJin** [facebookresearch/DensePose#79]
I got this warning when  visualizing the human-body FG mask indices. And the output is just like the origin picture.  Then I checked the INDS file generated by densepose, which is totally black. 

I run inference using the following commands.
`python2 tools/infer_simple.py \
    --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml \
    --output-dir DensePoseData/infer_out/ \
    --image-ext jpg \
    --wts https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl \
    DensePoseData/demo_data/demo_im.jpg`

Did I do anything wrong? The IUV file generated after inference is fine. But there is no data in the INDS file.

I am using Ubuntu 16.04, CUDA 8.0, cuDNN 6.0.21 and Tesla P100

**Comment by vkhalidov** [comment]
Please check how the INDS file is [generated](https://github.com/facebookresearch/DensePose/blob/master/detectron/utils/vis.py). Maybe index values are small and perceived as "totally black"?  I suggest you to check for non-zero values programmatically.

**Comment by tsing90** [comment]
@BryanJin  I have the same issue, how did you solve it? thanks

**Comment by tsing90** [comment]
I've found the answer here #127 , thanks for your issue.
