### ISSUE TITLE
Engine CUDNN is not available for operator MaxPool

### ISSUE THREAD

**Issue by minthetkhine** [facebookresearch/DensePose#80]
I installed Caffe2 using the Anaconda pre-built binary with CUDA 9.0 and cuDNN 7.1.4. infer_simple.py seems to work just fine without any errors, but I do not think that it is making use of the GPU, and it outputs warnings like:

`Engine CUDNN is not available for operator MaxPool`

Also, there have been new messages like `Created new CPU Pool size: 4; NUMA node id: -1`, but I don't think it should be using the CPU since I have the GPU. Does anyone know what's wrong?

**Comment by vkhalidov** [comment]
@minthetkhine First, CPU is used anyway along with the GPU, so you don't need to be surprised by the CPU-related message. For the cuDNN-related message, please check the answer of @bddppq in [caffe2/caffe2#2130](https://github.com/caffe2/caffe2/issues/2130)

**Comment by LovPe** [comment]
@minthetkhine i have the same issue!!!!! and i dont get correct result when running infer_simple.py , do
you run and get the currect instance segmentation result?

**Comment by minthetkhine** [comment]
@LovPe I do get correct results when running infer_simple.py, but it's running much too slow compared to when I did not have these CuDNN-related warnings.

**Comment by LovPe** [comment]
@minthetkhine 
can you pass the pass the Detectron tests:
python2 $DETECTRON/detectron/tests/test_spatial_narrow_as_op.py

**Comment by minthetkhine** [comment]
Yes.

**Comment by LovPe** [comment]
@minthetkhine it seems the anaconda prebuild problem...
 i build the caffe2 from source and finally fixed this problem. hope it helps you

**Comment by minthetkhine** [comment]
Can I have a look at your CMake output? I also tried building Caffe2 from source and I still get the cuDNN warnings.

**Comment by CarlosYeverino** [comment]
Hi,

I also get the cuDNN warnings. I built Caffe2 from source on ubuntu 16.04. @bddppq @vkhalidov Is there actually a cudnn implementation for Maxpool? If yes, any suggestions on how to fix this?

**Comment by minthetkhine** [comment]
I still have the warnings, but I think there should be because I used to be able to run infer_simple.py without those warnings earlier.

**Comment by LovPe** [comment]
Yes i still get this warning when training but it seems no harm to the speed I run maskrcnn on cityscapes using 2gpu and image size800_1600,  i get 0.67s/iter Chen LovPe 邮箱：qweewq375073115@gmail.com 签名由 网易邮箱大师 定制 On 07/30/2018 08:42, Min Thet Khine wrote: I still have the warnings, but I think there should be because I used to be able to run infer_simple.py without those warnings earlier. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by minthetkhine** [comment]
@LovPe Yes, you are right about the speed. It turns out that the warnings do not matter after all. In that case, I will go ahead and close this issue.

**Comment by Gouiaa** [comment]
@LovPe , I installed the binary version of caffe2 on ubuntu 18.04. I passed all the tests without any warning. When I try this test:
```
python2 tools/infer_simple.py \
    --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml \
    --output-dir DensePoseData/infer_out/ \
    --image-ext jpg \
    --wts https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl \
    DensePoseData/demo_data/demo_im.jpg 
```
I get these warnings :

> WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
> INFO net.py:  51: Loading weights from: /tmp/detectron-download-cache/DensePose_ResNet101_FPN_s1x-e2e.pkl
> I1127 11:45:32.273214  3827 operator.cc:195] Engine CUDNN is not available for operator MaxPool.
> I1127 11:45:32.278446  3827 operator.cc:195] Engine CUDNN is not available for operator MaxPool.
> I1127 11:45:32.279438  3827 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 6.6556e-05 secs
> I1127 11:45:32.282389  3827 operator.cc:195] Engine CUDNN is not available for operator MaxPool.
> I1127 11:45:32.287865  3827 operator.cc:195] Engine CUDNN is not available for operator MaxPool.

How did you resolve it please ?
