### ISSUE TITLE
About COCO DensePose Challenge

### ISSUE THREAD

**Issue by soeaver** [facebookresearch/DensePose#82]
Hi, thanks for your work. I want to take part in the coco DensePose competition, but I am very curious about which file is used to submit test phase? I submitted 'image_info_test-dev2017.json' but got bug.
![image](https://user-images.githubusercontent.com/8629203/43441804-a5fd701c-94ce-11e8-8922-b200b1db74d2.png)

**Comment by vkhalidov** [comment]
Sorry for that, the file with the images from the COCO DensePose test set is available [here](https://s3.amazonaws.com/densepose/densepose_coco_2014_test.json). The images from COCO test set 2015 are used.

**Comment by soeaver** [comment]
Great! I have succeeded in submitting the result.
