### ISSUE TITLE
Training Model for Keypoint Detection

### ISSUE THREAD

**Issue by minthetkhine** [facebookresearch/DensePose#83]
I want to detect keypoints from DensePose and from earlier issues, I read that we need to train our own models. I am not quite sure what the config file should be to train such a model with 1 GPU. Can anybody give me any hints? Thank you.

**Comment by nneverova** [comment]
@minthetkhine, you would need to add the following lines in your yaml file (see detectron configs for more info):

MODEL:
  KEYPOINTS_ON: True

KRCNN:
  ROI_KEYPOINTS_HEAD: keypoint_rcnn_heads.add_roi_pose_head_v1convX
  NUM_STACKED_CONVS: 8
  NUM_KEYPOINTS: 17 
  USE_DECONV: False
  USE_DECONV_OUTPUT: True 
  DECONV_KERNEL: 4 
  CONV_INIT: MSRAFill
  CONV_HEAD_KERNEL: 3
  CONV_HEAD_DIM: 512
  UP_SCALE: 2 
  HEATMAP_SIZE: 56 
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  KEYPOINT_CONFIDENCE: bbox

**Comment by minthetkhine** [comment]
Thank you.
