### ISSUE TITLE
number of parametrized mesh faces unequal to SMPL mesh faces

### ISSUE THREAD

**Issue by VVingerfly** [facebookresearch/DensePose#92]
Hi, 

First of all, thank you for making such a excellent work public available.

I downloaded the uv data and found the number of faces in the data is **13774**.  But there are **13776** faces in the SMPL mesh, which has two more faces.  

I wonder if there is anything I missed? How to make a correspondence between the uv coordinates and SMPL mesh vertices?

Thanks a lot!

**Comment by GianKiMoon** [comment]
Hi, did you found out how to make the correspondence between the uv coordinates and SMPL mesh vertices? Thanks for your help!

**Comment by VVingerfly** [comment]
@GianKiMoon hi, the mesh DensePose provided has 2 missing triangles on the left and right foot thumb. The correspondence is provided by DensePose.

**Comment by VVingerfly** [comment]
@zhhezhhe

**Comment by zhhezhhe** [comment]
I use Maya to render images with 13774 and 13776 faces, respectively. But the results looks wrong.
13774. I just use the SMPL demo code. I don't know why. Anyone can help?: 
code looks like:
```
ALP_UV = loadmat( os.path.join(os.path.dirname(__file__), '/UV_data/UV_Processed.mat')  )
FacesDensePose = ALP_UV['All_Faces']-1
m = load_model( '../../models/basicmodel_m_lbs_10_207_0_v1.0.0.pkl' )
with open( outmesh_path, 'w') as fp:
    for v in m.r:
        fp.write( 'v %f %f %f\n' % ( v[0], v[1], v[2]) )
    for f in FacesDensePose+1: # Faces are 1-based, not 0-based in obj files
        fp.write( 'f %d %d %d\n' %  (f[0], f[1], f[2]) )
```

![image](https://user-images.githubusercontent.com/16225495/49637212-b74d9a00-fa3f-11e8-9b33-1ced0bb7cb45.png)

while 13776 is the right image.
code looks like:
```
with open( outmesh_path, 'w') as fp:
    for v in m.r:
        fp.write( 'v %f %f %f\n' % ( v[0], v[1], v[2]) )

    for f in m.f+1: # Faces are 1-based, not 0-based in obj files
        fp.write( 'f %d %d %d\n' %  (f[0], f[1], f[2]) )
```
![image](https://user-images.githubusercontent.com/16225495/49637255-d51aff00-fa3f-11e8-8b26-f9b7df37a14e.png)

**Comment by Rhyssiyan** [comment]
@VVingerfly  I have some confusion. I found there are 7829 vertices in the 'All_vertices' key and there are only 6890 vertices in the SMPL model. So Are there overlaps between different parts? Thanks for your help.

**Comment by zhhezhhe** [comment]
I think there are overlaps only in the same part. There are no overlaps between different parts. Am I right.

**Comment by zhhezhhe** [comment]
@Rhyssiyan I think there are overlaps only in the same part. There are no overlaps between different parts. Am I right.

**Comment by Rhyssiyan** [comment]
Hi @zhhezhhe ,  I find that the same vertice in the SMPL model has different U_norm values. For example, the vertices 6493,7810 in ALP_UV['All_vertices'] correspond to the same vertice 3073 in the SMPL model fot the demo data. However, ALP_UV['All_U_norm'][6493]= 0.99689119, ALP_UV['All_U_norm'][7810]= 0.00137981. I'm trying to figure out

**Comment by Rhyssiyan** [comment]
Hi @zhhezhhe ,  thanks for the discussion. I think there exists overlaps between different parts. There is a case in the demo data. I will take vertice 3073 in the SMPL model as an example. 
![image](https://user-images.githubusercontent.com/30871303/61703775-e61d4400-ad74-11e9-9031-ad2dfbd8d59f.png)
The vertices 6493,7810 in ALP_UV['All_vertices'] correspond to the same vertice 3073 for the demo data.
![image](https://user-images.githubusercontent.com/30871303/61703952-41e7cd00-ad75-11e9-80e9-d04b09d4e268.png)
From the above figure, we can see that the faces are different for the vertice 6493 and 7810. So I think there are overlaps between different parts.

**Comment by zhhezhhe** [comment]
@Rhyssiyan I think you are right. It make sense.

**Comment by VVingerfly** [comment]
@Rhyssiyan Hi, 'All_vertices' are the vertices of the 24 parts of the original SMPL mesh, so there will be more vertices in the seams after you cut the original closed mesh.

**Comment by Rhyssiyan** [comment]
Thanks for your helpful reply. I have another question. Is 'All_vertices' obtained by cutting the mesh in 'basicmodel_m_lbs_10_207_0_v1.0.0.pkl'?  In other words, Isn't pose information included in the ground truth uv map for densepose? What we regress is the coordinates for the standard T-pose. Is it true?

**Comment by VVingerfly** [comment]
@Rhyssiyan 'All_vertices' is obtained by cutting the T-pose mesh.
DensePose regress the uv coordinates of the pixels in the color image, which are correspondent to the 3d vertex of the T-pose mesh.

**Comment by Rhyssiyan** [comment]
Thank you! It solves my confusion.
