### ISSUE TITLE
stop printing gpu info

### ISSUE THREAD

**Issue by penincillin** [facebookresearch/DensePose#96]
Hi, during training, too much gpu info like below was printed on the screen.

I0816 17:52:58.091966 28298 context_gpu.cu:321] GPU 0: 151 MB
I0816 17:52:58.091997 28298 context_gpu.cu:325] Total: 151 MB
I0816 17:52:58.681579 28298 context_gpu.cu:321] GPU 0: 225 MB
I0816 17:52:58.681613 28298 context_gpu.cu:321] GPU 1: 55 MB
I0816 17:52:58.681618 28298 context_gpu.cu:325] Total: 281 MB
I0816 17:52:58.909143 28298 context_gpu.cu:321] GPU 0: 225 MB
I0816 17:52:58.909185 28298 context_gpu.cu:321] GPU 1: 186 MB
I0816 17:52:58.909195 28298 context_gpu.cu:325] Total: 412 MB
I0816 17:53:00.161229 28298 context_gpu.cu:321] GPU 0: 225 MB
I0816 17:53:00.161281 28298 context_gpu.cu:321] GPU 1: 225 MB
I0816 17:53:00.161290 28298 context_gpu.cu:321] GPU 2: 89 MB
I0816 17:53:00.161298 28298 context_gpu.cu:325] Total: 541 MB
I0816 17:53:00.361152 28298 context_gpu.cu:321] GPU 0: 225 MB
I0816 17:53:00.361188 28298 context_gpu.cu:321] GPU 1: 225 MB
I0816 17:53:00.361196 28298 context_gpu.cu:321] GPU 2: 222 MB
I0816 17:53:00.361202 28298 context_gpu.cu:325] Total: 674 MB
I0816 17:53:01.141896 28298 context_gpu.cu:321] GPU 0: 225 MB
I0816 17:53:01.141952 28298 context_gpu.cu:321] GPU 1: 225 MB
I0816 17:53:01.141961 28298 context_gpu.cu:321] GPU 2: 225 MB
I0816 17:53:01.141969 28298 context_gpu.cu:321] GPU 3: 151 MB
I0816 17:53:01.141978 28298 context_gpu.cu:325] Total: 829 MB
I0816 17:53:01.596585 28298 context_gpu.cu:321] GPU 0: 280 MB
I0816 17:53:01.596632 28298 context_gpu.cu:321] GPU 1: 225 MB
I0816 17:53:01.596640 28298 context_gpu.cu:321] GPU 2: 225 MB
I0816 17:53:01.596649 28298 context_gpu.cu:321] GPU 3: 225 MB
I0816 17:53:01.596657 28298 context_gpu.cu:325] Total: 958 MB

Is there a way to stop printing this "useless" gpu info?
Thanks

**Comment by vkhalidov** [comment]
@penincillin, if you want to change logging settings, you can adjust [this line](https://github.com/facebookresearch/DensePose/blob/master/tools/train_net.py#L80)
